"""Generator for notebooks/01_agent_loop.ipynb."""

from build_notebook import code, md, write

cells = [
    md(
        "# 01 — The Agent Loop\n"
        "\n"
        "> *\"Every major AI agent runs the same core loop. A `while` loop that calls an LLM, "
        "checks if the response contains tool calls, executes them if it does, and stops if it doesn't.\"*\n"
        "\n"
        "**By the end of this notebook you will:**\n"
        "1. Write the 6-line agent loop from memory\n"
        "2. Watch it succeed on a normal input\n"
        "3. Break it on purpose to see real failure modes\n"
        "4. Add the four production necessities: bounded steps, parallel tool calls, error isolation, observability\n"
        "\n"
        "Lecture reference: **S8 §3** (*Implementing the Agent Loop*).\n"
    ),
    md(
        "## Setup"
    ),
    code(
        "import asyncio\n"
        "import json\n"
        "import os\n"
        "from dotenv import load_dotenv\n"
        "from openai import AsyncOpenAI\n"
        "\n"
        "load_dotenv()\n"
        "client = AsyncOpenAI()\n"
        "MODEL = os.getenv(\"OPENAI_MODEL\", \"gpt-4o-mini\")\n"
        "print(f\"Using model: {MODEL}\")"
    ),
    md(
        "## 1. The 6-line agent loop\n"
        "\n"
        "This is the entire idea of an LLM agent in 6 lines of meaningful code. Memorise it.\n"
        "\n"
        "```\n"
        "while not done:\n"
        "    msg = llm(messages, tools=tools)        # 1. ask\n"
        "    messages.append(msg)                    # 2. remember\n"
        "    if not msg.tool_calls: return msg.text  # 3. natural exit\n"
        "    for tc in msg.tool_calls:               # 4. act\n"
        "        result = execute(tc)                # 5. observe\n"
        "        messages.append(result)             # 6. remember the observation\n"
        "```\n"
        "\n"
        "Below is the working version with one knob: `max_steps` to prevent infinite loops."
    ),
    code(
        "async def run_agent_v0(user_msg, tools, executors, max_steps=10):\n"
        "    \"\"\"The 6-line agent loop. No safety nets — break it to learn what production needs.\"\"\"\n"
        "    messages = [{\"role\": \"user\", \"content\": user_msg}]\n"
        "    for _ in range(max_steps):\n"
        "        resp = await client.chat.completions.create(model=MODEL, messages=messages, tools=tools)\n"
        "        msg = resp.choices[0].message\n"
        "        messages.append(msg.model_dump(exclude_unset=True))\n"
        "        if not msg.tool_calls:\n"
        "            return msg.content\n"
        "        for tc in msg.tool_calls:\n"
        "            result = executors[tc.function.name](**json.loads(tc.function.arguments))\n"
        "            messages.append({\"role\": \"tool\", \"tool_call_id\": tc.id, \"content\": json.dumps(result)})\n"
        "    raise RuntimeError(\"max_steps exceeded\")"
    ),
    md(
        "## 2. Try it with one tool\n"
        "\n"
        "We give it a single tool: `add(a, b)`. The model has to *decide* to call this tool to compute "
        "`17 + 25` rather than computing it itself in text.\n"
        "\n"
        "Notice the schema declares `additionalProperties: False` — that's required when you turn on `strict: True`. "
        "We'll cover strict mode in detail in notebook 02.\n"
    ),
    code(
        "TOOLS = [{\n"
        "    \"type\": \"function\",\n"
        "    \"function\": {\n"
        "        \"name\": \"add\",\n"
        "        \"description\": \"Add two integers and return the sum.\",\n"
        "        \"parameters\": {\n"
        "            \"type\": \"object\",\n"
        "            \"properties\": {\"a\": {\"type\": \"integer\"}, \"b\": {\"type\": \"integer\"}},\n"
        "            \"required\": [\"a\", \"b\"],\n"
        "            \"additionalProperties\": False,\n"
        "        },\n"
        "        \"strict\": True,\n"
        "    },\n"
        "}]\n"
        "\n"
        "EXECUTORS = {\"add\": lambda a, b: {\"sum\": a + b}}\n"
        "\n"
        "answer = await run_agent_v0(\"What is 17 + 25?\", TOOLS, EXECUTORS)\n"
        "print(answer)"
    ),
    md(
        "## 3. Break it: hallucinated tool\n"
        "\n"
        "What happens if the LLM tries to call a tool that doesn't exist?\n"
        "\n"
        "Ask it to multiply — but we only registered `add`. Watch what happens to your runtime."
    ),
    code(
        "try:\n"
        "    answer = await run_agent_v0(\"What is 7 times 8?\", TOOLS, EXECUTORS)\n"
        "    print(answer)\n"
        "except Exception as e:\n"
        "    print(f\"💥 {type(e).__name__}: {e}\")"
    ),
    md(
        "**The whole agent crashes.** A real production agent must convert tool errors into "
        "*observations the LLM can read*, not exceptions that crash the runtime. Then the LLM "
        "usually self-corrects on the next turn (\"oh, I should use `add` repeatedly\")."
    ),
    md(
        "## 4. Production-hardened loop\n"
        "\n"
        "We'll add four things:\n"
        "\n"
        "| Add | Why |\n"
        "|---|---|\n"
        "| `parallel_tool_calls=True` | independent tool calls happen in one round-trip |\n"
        "| `try/except` around tool execution | errors become tool results, not crashes |\n"
        "| `trace` list | every step is observable — see S8 §7 |\n"
        "| graceful `tool_choice=\"none\"` final call | when `max_steps` hit, force a text answer |\n"
        "\n"
        "Other refinements we'll cover later — strict mode (notebook 02), loop fingerprinting and "
        "cost caps (notebook 03)."
    ),
    code(
        "async def run_agent(user_msg, tools, executors, system=None, max_steps=10, model=None):\n"
        "    model = model or MODEL\n"
        "    messages = []\n"
        "    if system:\n"
        "        messages.append({\"role\": \"system\", \"content\": system})\n"
        "    messages.append({\"role\": \"user\", \"content\": user_msg})\n"
        "    trace = []\n"
        "\n"
        "    for step in range(max_steps):\n"
        "        resp = await client.chat.completions.create(\n"
        "            model=model,\n"
        "            messages=messages,\n"
        "            tools=tools,\n"
        "            tool_choice=\"auto\",\n"
        "            parallel_tool_calls=True,\n"
        "        )\n"
        "        msg = resp.choices[0].message\n"
        "        messages.append(msg.model_dump(exclude_unset=True))\n"
        "        trace.append({\n"
        "            \"step\": step,\n"
        "            \"tokens\": resp.usage.total_tokens,\n"
        "            \"tool_calls\": [tc.function.name for tc in (msg.tool_calls or [])],\n"
        "            \"content\": msg.content,\n"
        "        })\n"
        "\n"
        "        # Natural exit — no more tool calls\n"
        "        if not msg.tool_calls:\n"
        "            return {\"answer\": msg.content, \"steps\": step + 1, \"trace\": trace, \"terminated_by\": \"natural\"}\n"
        "\n"
        "        # Execute tool calls — convert any error into an observation the LLM can read\n"
        "        for tc in msg.tool_calls:\n"
        "            try:\n"
        "                args = json.loads(tc.function.arguments)\n"
        "                fn = executors.get(tc.function.name)\n"
        "                if fn is None:\n"
        "                    raise KeyError(f\"Unknown tool: {tc.function.name}. Available: {list(executors)}\")\n"
        "                result = await fn(**args) if asyncio.iscoroutinefunction(fn) else fn(**args)\n"
        "                content = json.dumps({\"success\": True, \"data\": result})\n"
        "            except Exception as e:\n"
        "                content = json.dumps({\"success\": False, \"error\": str(e)})\n"
        "            messages.append({\"role\": \"tool\", \"tool_call_id\": tc.id, \"content\": content})\n"
        "\n"
        "    # Max steps hit — force a final text answer instead of raising\n"
        "    messages.append({\n"
        "        \"role\": \"user\",\n"
        "        \"content\": \"Max steps reached. Provide your best answer based on what you've learned. Do not call any more tools.\",\n"
        "    })\n"
        "    final = await client.chat.completions.create(model=model, messages=messages, tool_choice=\"none\")\n"
        "    return {\n"
        "        \"answer\": final.choices[0].message.content,\n"
        "        \"steps\": max_steps,\n"
        "        \"trace\": trace,\n"
        "        \"terminated_by\": \"max_steps\",\n"
        "    }"
    ),
    md(
        "## 5. Re-run the broken case\n"
        "\n"
        "Same input that crashed `run_agent_v0` — now the agent survives and the LLM gets a chance to recover."
    ),
    code(
        "result = await run_agent(\n"
        "    \"What is 7 times 8? You can only add.\",\n"
        "    TOOLS,\n"
        "    EXECUTORS,\n"
        "    system=\"You are a helpful assistant. Use the available tools.\",\n"
        ")\n"
        "print(\"answer:\", result[\"answer\"])\n"
        "print(\"\\ntrace:\")\n"
        "for entry in result[\"trace\"]:\n"
        "    calls = entry[\"tool_calls\"] or \"—\"\n"
        "    print(f\"  step {entry['step']}: tools={calls}  tokens={entry['tokens']}\")"
    ),
    md(
        "What you should see: the LLM calls `add` with progressively larger arguments to compute `7×8 = 56`. "
        "It treats the missing `multiply` as a constraint and works around it. **That's the LLM self-correcting "
        "from a tool-result observation** — exactly what makes ReAct different from plain chain-of-thought.\n"
    ),
    md(
        "## 6. Parallel tool calls\n"
        "\n"
        "When the LLM has *independent* sub-questions it can issue multiple tool calls in a single turn. "
        "`parallel_tool_calls=True` lets that happen. Without it you'd get N round-trips for N independent calls.\n"
        "\n"
        "Watch the `tool_calls` column in the trace below."
    ),
    code(
        "result = await run_agent(\n"
        "    \"Compute 1+1, 2+2, and 3+3 — give me all three answers.\",\n"
        "    TOOLS,\n"
        "    EXECUTORS,\n"
        ")\n"
        "print(\"answer:\", result[\"answer\"])\n"
        "print(\"\\ntrace:\")\n"
        "for entry in result[\"trace\"]:\n"
        "    print(f\"  step {entry['step']}: {entry['tool_calls']}\")"
    ),
    md(
        "Step 0 should show `['add', 'add', 'add']` — three tool calls in one turn. Step 1 is the final answer.\n"
        "\n"
        "Without parallel calls you'd see three separate steps each with one call."
    ),
    md(
        "## 7. Self-check\n"
        "\n"
        "Before moving on, can you answer these without scrolling up?\n"
        "\n"
        "1. Write `run_agent_v0` from memory. (6-ish lines.)\n"
        "2. Name three things `run_agent_v0` is missing for production.\n"
        "3. What does `tool_choice=\"none\"` guarantee about the next assistant message?\n"
        "4. Why do we wrap tool execution in `try/except` instead of letting it raise?\n"
        "5. What's the difference between `terminated_by=\"natural\"` and `terminated_by=\"max_steps\"`?\n"
        "\n"
        "## What's next\n"
        "\n"
        "Notebook **02** turns the loose `TOOLS` and `EXECUTORS` dicts into proper `BaseTool` and "
        "`ToolRegistry` classes — and digs into OpenAI's `strict: True` mode (the production must-have for "
        "preventing argument-shape hallucinations).\n"
    ),
]

write("notebooks/01_agent_loop.ipynb", cells)
print("wrote notebooks/01_agent_loop.ipynb")
