"""Generator for notebooks/01_agent_loop.ipynb."""

from build_notebook import code, md, write

cells = [
    md(
        "# 01 — The Agent Loop\n"
        "\n"
        "> *\"Every major AI agent runs the same core loop. A `while` loop that calls an LLM, "
        "checks if the response contains tool calls, executes them if it does, and stops if it doesn't.\"*\n"
        "\n"
        "**By the end of this notebook you will:**\n"
        "1. Write the 6-line agent loop from memory\n"
        "2. Watch what really happens — including the **cognitive-shortcut** behavior where the model "
        "ignores your tools and answers from training\n"
        "3. See the loop actually do useful multi-step work when forced\n"
        "4. Add the four production necessities: bounded steps, parallel tool calls, error isolation, observability\n"
        "\n"
        "Lecture reference: **S8 §3** (*Implementing the Agent Loop*).\n"
    ),
    md(
        "## Setup"
    ),
    code(
        "import asyncio\n"
        "import json\n"
        "import os\n"
        "from dotenv import load_dotenv\n"
        "from openai import AsyncOpenAI\n"
        "\n"
        "load_dotenv()\n"
        "client = AsyncOpenAI()\n"
        "MODEL = os.getenv(\"OPENAI_MODEL\", \"gpt-4o-mini\")\n"
        "print(f\"Using model: {MODEL}\")"
    ),
    md(
        "## 1. The 6-line agent loop\n"
        "\n"
        "This is the entire idea of an LLM agent in 6 lines of meaningful code:\n"
        "\n"
        "```\n"
        "while not done:\n"
        "    msg = llm(messages, tools=tools)        # 1. ask\n"
        "    messages.append(msg)                    # 2. remember\n"
        "    if not msg.tool_calls: return msg.text  # 3. natural exit\n"
        "    for tc in msg.tool_calls:               # 4. act\n"
        "        result = execute(tc)                # 5. observe\n"
        "        messages.append(result)             # 6. remember the observation\n"
        "```\n"
        "\n"
        "Below is the working version. The **core 6 lines** are still in there — everything else "
        "(the `print()` calls, the `max_steps` cap) is for visibility, not the algorithm. Watching the "
        "prompt evolve at every step is the whole point of this notebook."
    ),
    code(
        "async def run_agent_v0(user_msg, tools, executors, max_steps=10):\n"
        "    \"\"\"The 6-line agent loop with verbose tracing. Break it on purpose to learn.\"\"\"\n"
        "    messages = [{\"role\": \"user\", \"content\": user_msg}]\n"
        "\n"
        "    for i in range(max_steps):\n"
        "        print(f\"\\n{'='*20} STEP {i+1} PROMPT {'='*20}\")\n"
        "        for m in messages:\n"
        "            role = m.get(\"role\")\n"
        "            content = m.get(\"content\") or (m.get(\"tool_calls\") if \"tool_calls\" in m else \"\")\n"
        "            print(f\"[{role.upper()}]: {content}\")\n"
        "\n"
        "        resp = await client.chat.completions.create(model=MODEL, messages=messages, tools=tools)\n"
        "        msg = resp.choices[0].message\n"
        "        messages.append(msg.model_dump(exclude_unset=True))\n"
        "\n"
        "        # Show what the model produced this turn — both its reasoning text and (if any) tool calls.\n"
        "        # On a tool-calling turn msg.content is often empty (model says nothing, just calls tools).\n"
        "        # On a natural-exit turn msg.content holds the final answer.\n"
        "        if msg.tool_calls:\n"
        "            reasoning = msg.content or \"(no text — model emitted only tool calls)\"\n"
        "            print(f\"\\n[MODEL REASONING]: {reasoning}\")\n"
        "        else:\n"
        "            print(f\"\\n[FINAL RESPONSE]: {msg.content or '(empty)'}\")\n"
        "            return msg.content\n"
        "\n"
        "        for tc in msg.tool_calls:\n"
        "            func_name = tc.function.name\n"
        "            args = tc.function.arguments\n"
        "            print(f\"\\n[TOOL CALL]: Calling {func_name} with {args}\")\n"
        "\n"
        "            result = executors[func_name](**json.loads(args))\n"
        "\n"
        "            print(f\"[TOOL RESULT]: {result}\")\n"
        "\n"
        "            messages.append({\"role\": \"tool\", \"tool_call_id\": tc.id, \"content\": json.dumps(result)})\n"
        "\n"
        "    raise RuntimeError(\"max_steps exceeded\")"
    ),
    md(
        "## 2. Try it with one tool\n"
        "\n"
        "Single tool: `add`. The model has to *decide* to call this tool to compute `17 + 25` rather "
        "than computing it itself in text.\n"
        "\n"
        "Schema note: `additionalProperties: False` is required when `strict: True` is on — we cover "
        "strict mode in detail in notebook 02."
    ),
    code(
        "TOOLS = [{\n"
        "    \"type\": \"function\",\n"
        "    \"function\": {\n"
        "        \"name\": \"add\",\n"
        "        \"description\": \"Add two integers and return the sum.\",\n"
        "        \"parameters\": {\n"
        "            \"type\": \"object\",\n"
        "            \"properties\": {\"a\": {\"type\": \"integer\"}, \"b\": {\"type\": \"integer\"}},\n"
        "            \"required\": [\"a\", \"b\"],\n"
        "            \"additionalProperties\": False,\n"
        "        },\n"
        "        \"strict\": True,\n"
        "    },\n"
        "}]\n"
        "\n"
        "EXECUTORS = {\"add\": lambda a, b: {\"sum\": a + b}}\n"
        "\n"
        "answer = await run_agent_v0(\"What is 17 + 25?\", TOOLS, EXECUTORS)"
    ),
    md(
        "Two steps. Step 1 — model calls `add(17, 25)` → 42. Step 2 — model has the tool result, "
        "produces the final answer.\n"
        "\n"
        "Read the **STEP 2 PROMPT** carefully. Notice what's in the messages list:\n"
        "1. The original user question\n"
        "2. The assistant message — content is empty, `tool_calls` field has the `add(17, 25)` call\n"
        "3. The tool result — `{\"sum\": 42}`\n"
        "\n"
        "**That's how ReAct works.** The model sees its own prior decisions AND the tool observations "
        "on every iteration — that's how it can reason about whether it's done.\n"
        "\n"
        "### How to read the trace output\n"
        "\n"
        "| Line | What it shows |\n"
        "|---|---|\n"
        "| `===== STEP N PROMPT =====` | the conversation history about to be sent to the LLM |\n"
        "| `[USER]:` / `[ASSISTANT]:` / `[TOOL]:` | one message in the history |\n"
        "| `[MODEL REASONING]:` | what text the model wrote *this turn* — its \"thinking out loud\" |\n"
        "| `[TOOL CALL]: Calling X with {...}` | the model decided to call tool X |\n"
        "| `[TOOL RESULT]: {...}` | what our executor returned |\n"
        "| `[FINAL RESPONSE]:` | the model wrote text without calling tools → loop exits |\n"
        "\n"
        "**About `[MODEL REASONING]`** — when the model emits tool calls, it usually says *nothing* "
        "alongside them (`msg.content` is `None`). You'll see `(no text — model emitted only tool calls)`. "
        "That's normal for `gpt-4o-mini`. **Reasoning-token models** (`o1`, `o3-mini`) and prompted "
        "\"think out loud\" agents will fill this in with their reasoning chain — that's where it gets "
        "interesting for debugging.\n"
    ),
    md(
        "## 3. Break it — and watch the model improvise\n"
        "\n"
        "Now the interesting test. Ask the agent to **multiply**. We only registered `add`. There's no "
        "`multiply` tool.\n"
        "\n"
        "Before you run it, write down what you predict will happen. Pick one:\n"
        "- (a) The model hallucinates a `multiply` tool name → `KeyError` crashes the agent\n"
        "- (b) The model loops with `add` to compute 7+7+7+7+7+7+7+7 = 56 (full grounded loop)\n"
        "- (c) The model calls `add(7, 8)` once, sees 15, then declares 56 from memory\n"
        "- (d) The model ignores your tool entirely and just answers from training data\n"
        "- (e) The model loops with `add` partially (a few times), then jumps to 56 from memory\n"
        "\n"
        "Now run it. Then run it again. Then run it a third time."
    ),
    code(
        "answer = await run_agent_v0(\"What is 7 times 8?\", TOOLS, EXECUTORS)"
    ),
    md(
        "Run that cell **at least three times** before reading on. Watch how the trace differs across "
        "runs. **Same model, same prompt, same tools** — different behavior across runs.\n"
        "\n"
        "These are three trace shapes we've observed for this exact prompt on `gpt-4o-mini` 2026 — "
        "none is rare, distribution varies by minor model version and decoding seed:\n"
        "\n"
        "**Trace shape A** — *partial loop + late bypass*:\n"
        "```\n"
        "step 1: add(7, 7) = 14          ← starts repeated-addition reasoning\n"
        "step 2: add(14, 7) = 21\n"
        "step 3: add(21, 7) = 28\n"
        "step 4: FINAL — \"7 times 8 equals 56.\"   ← jumps from 28 (= 4×7) to 56 from memory\n"
        "```\n"
        "\n"
        "**Trace shape B** — *immediate bypass with self-acknowledgment*:\n"
        "```\n"
        "step 1: add(7, 8) = 15          ← picks the closest tool, gets the wrong-domain answer\n"
        "step 2: FINAL — \"The sum of 7 and 8 is 15. However, 7 times 8 is actually 56.\"\n"
        "                                 ↑ model EXPLICITLY admits it's overriding the tool result\n"
        "```\n"
        "\n"
        "Pay attention to shape B — the model is **openly telling you** it's bypassing the tool. That's a "
        "rare moment of model honesty: most cognitive-shortcut bypasses are silent (shape A). If your "
        "production trace logs every model utterance, shape B is detectable via the \"However, X is "
        "actually Y\" hedge phrase. Shape A is not — that's why it's the dangerous one.\n"
        "\n"
        "**Trace shape C** — *full grounded loop* (rare on `gpt-4o-mini`, more common on `gpt-4o`):\n"
        "```\n"
        "step 1-7: add(7, 7), add(14, 7), add(21, 7), add(28, 7), add(35, 7), add(42, 7), add(49, 7)\n"
        "step 8: FINAL — \"56.\"\n"
        "```\n"
        "\n"
        "**Two lessons stacked here. Both are senior-level.**\n"
    ),
    md(
        "### Lesson 1 — Agents are non-deterministic\n"
        "\n"
        "Same input → different traces. `temperature=1.0` (the default) means the model samples; tool "
        "choice is a sample; even the number of loop iterations is a sample. **You cannot reason about "
        "agent behavior from a single trace.**\n"
        "\n"
        "Production teams test with N runs (typically 10-50) against a fixed eval set and report "
        "**distributions**: \"the agent calls the right tool 87% of the time\" — not \"the agent calls "
        "the right tool\" (a meaningless statement). This is why eval frameworks (Langfuse, Braintrust, "
        "LangSmith) all default to multi-run sampling.\n"
        "\n"
        "**Interview signal:** if someone shows you one happy-path trace and concludes \"the agent "
        "works,\" they haven't shipped agents in production."
    ),
    md(
        "### Lesson 2 — Partial loop + late bypass is the dangerous failure mode\n"
        "\n"
        "Trace shape A — the *partial-loop* one — is what you should be afraid of.\n"
        "\n"
        "The model **used the tool a few times**, then **jumped to a memory answer for the final step**. "
        "The trace looks like the agent was using your tool. The final answer was NOT grounded in the "
        "tool. The user reading the answer can't tell the difference.\n"
        "\n"
        "Why this is dangerous:\n"
        "- **Trace inspection is fooled** — \"I see 3 tool calls in the log, so the agent used tools.\" "
        "But the *final answer* didn't use the tool result.\n"
        "- **Grounding guarantees are broken** — if the whole point of the tool was real-time data "
        "(stock price, inventory count, DB lookup), the answer is *not* grounded even though tools were called.\n"
        "- **Hard to detect at scale** — the answer might be right, might be wrong; you only catch it on "
        "the wrong ones, and you only catch wrong ones via downstream complaints.\n"
        "\n"
        "**Senior interview answer:** *\"The classic agent failure mode in 2026 isn't hallucinated tool "
        "names — modern models rarely do that. It's the **partial-grounding** problem: the model calls "
        "tools for a few steps, then synthesizes a final answer that bypasses the latest tool results. "
        "Trace counts are not grounding proofs. To enforce grounding you need either output validators "
        "that check the answer is derivable from the captured tool results, or structured outputs that "
        "reference tool call IDs by construction.\"*\n"
        "\n"
        "**The 2023→2026 narrative shift:**\n"
        "\n"
        "| What 2023 tutorials said | What 2026 models actually do |\n"
        "|---|---|\n"
        "| LLMs hallucinate tool names | Modern LLMs (`gpt-4o-mini`+) rarely do; they pick *closest* tool instead |\n"
        "| The ReAct loop forces tool use | The loop forces nothing — the model can answer from training at any step |\n"
        "| You can read the trace to verify the agent used tools | You need to verify the *final answer* came from tool data, not just that tools were *called* |\n"
        "| Single happy-path trace = it works | N-run distributions across an eval set = it (probably) works |\n"
        "\n"
        "**The implication for engineers**: run your agent 10 times against representative inputs. "
        "Inspect the **distribution** of trace shapes. The boring ones are fine — the failure-mode ones "
        "tell you what to defend against."
    ),
    md(
        "## 4. Force the loop — when the model really *has* to call the tool\n"
        "\n"
        "If you want to see the loop genuinely doing multi-step work, you need a problem the model "
        "**can't shortcut from memory**. Big numbers work — `gpt-4o-mini` doesn't reliably add "
        "5-digit numbers from training, so it defers to the tool.\n"
        "\n"
        "Try this:"
    ),
    code(
        "answer = await run_agent_v0(\n"
        "    \"Use the add tool to compute the running total of these numbers, one at a time: \"\n"
        "    \"12345, 67890, 11111, 22222. Report each intermediate total before the final.\",\n"
        "    TOOLS, EXECUTORS,\n"
        ")"
    ),
    md(
        "Read the trace top-to-bottom. A typical run produces something like:\n"
        "\n"
        "- **Step 1** — model calls `add(12345, 0)` → `{\"sum\": 12345}`  ← see note below\n"
        "- **Step 2** — model calls `add(67890, 12345)` → `{\"sum\": 80235}`\n"
        "- **Step 3** — model calls `add(11111, 80235)` → `{\"sum\": 91346}`\n"
        "- **Step 4** — model calls `add(22222, 91346)` → `{\"sum\": 113568}`\n"
        "- **Step 5** — final response with all four running totals\n"
        "\n"
        "**About that `add(12345, 0)` first call** — the model interprets *\"report each intermediate "
        "total\"* literally and treats the first number itself as an intermediate, so it calls the tool "
        "with `b=0` just to \"emit\" the value through the tool channel. **This is the model being "
        "weirdly literal about the prompt**, not a bug. It's a real, interesting LLM behavior to call "
        "out — `n+1` tool calls instead of `n`, because the model is making the first input addressable "
        "as a tool result for the final summary.\n"
        "\n"
        "Some runs skip the `+0` call and start directly with `add(12345, 67890)`. Both are valid "
        "interpretations. **This is the non-determinism point again** — even on a forced-loop prompt, "
        "exact step count varies.\n"
        "\n"
        "**This is ReAct working as advertised.** Each step the model:\n"
        "1. Reads the previous tool result from the conversation history\n"
        "2. Decides what to do next based on it\n"
        "3. Either calls another tool or stops\n"
        "\n"
        "Compare this trace with §3 above. Same loop. Same model. Same tool. Completely different "
        "behavior — driven entirely by whether the prompt forces tool use.\n"
        "\n"
        "**The lesson is the contrast, not either trace alone.** In §3 the model bypassed the tool. "
        "In §4 it didn't. Production engineers run **both** kinds of trace before claiming an agent works."
    ),
    md(
        "## 5. What's missing for production\n"
        "\n"
        "`run_agent_v0` is fine for learning. It's not safe for production. Four gaps:\n"
        "\n"
        "| Gap | What it costs you |\n"
        "|---|---|\n"
        "| No `parallel_tool_calls=True` | independent tool calls happen serially — extra round-trip per call |\n"
        "| No `try/except` around tool execution | unknown tool name or args error = **agent crashes**, user sees 500 |\n"
        "| `print()` is your only trace | great for notebooks, useless for ops at scale |\n"
        "| `raise RuntimeError` on max_steps | user gets a 500 instead of \"here's my best answer so far\" |\n"
        "\n"
        "Let's fix all four."
    ),
    code(
        "async def run_agent(user_msg, tools, executors, system=None, max_steps=10, model=None):\n"
        "    model = model or MODEL\n"
        "    messages = []\n"
        "    if system:\n"
        "        messages.append({\"role\": \"system\", \"content\": system})\n"
        "    messages.append({\"role\": \"user\", \"content\": user_msg})\n"
        "    trace = []\n"
        "\n"
        "    for step in range(max_steps):\n"
        "        resp = await client.chat.completions.create(\n"
        "            model=model,\n"
        "            messages=messages,\n"
        "            tools=tools,\n"
        "            tool_choice=\"auto\",\n"
        "            parallel_tool_calls=True,\n"
        "        )\n"
        "        msg = resp.choices[0].message\n"
        "        messages.append(msg.model_dump(exclude_unset=True))\n"
        "        trace.append({\n"
        "            \"step\": step,\n"
        "            \"tokens\": resp.usage.total_tokens,\n"
        "            \"tool_calls\": [tc.function.name for tc in (msg.tool_calls or [])],\n"
        "            \"content\": msg.content,\n"
        "        })\n"
        "\n"
        "        # Natural exit — no more tool calls\n"
        "        if not msg.tool_calls:\n"
        "            return {\"answer\": msg.content, \"steps\": step + 1, \"trace\": trace, \"terminated_by\": \"natural\"}\n"
        "\n"
        "        # Execute tool calls — convert any error into an observation the LLM can read\n"
        "        for tc in msg.tool_calls:\n"
        "            try:\n"
        "                args = json.loads(tc.function.arguments)\n"
        "                fn = executors.get(tc.function.name)\n"
        "                if fn is None:\n"
        "                    raise KeyError(f\"Unknown tool: {tc.function.name}. Available: {list(executors)}\")\n"
        "                result = await fn(**args) if asyncio.iscoroutinefunction(fn) else fn(**args)\n"
        "                content = json.dumps({\"success\": True, \"data\": result})\n"
        "            except Exception as e:\n"
        "                content = json.dumps({\"success\": False, \"error\": str(e)})\n"
        "            messages.append({\"role\": \"tool\", \"tool_call_id\": tc.id, \"content\": content})\n"
        "\n"
        "    # Max steps hit — force a final text answer instead of raising\n"
        "    messages.append({\n"
        "        \"role\": \"user\",\n"
        "        \"content\": \"Max steps reached. Provide your best answer based on what you've learned. Do not call any more tools.\",\n"
        "    })\n"
        "    final = await client.chat.completions.create(model=model, messages=messages, tool_choice=\"none\")\n"
        "    return {\n"
        "        \"answer\": final.choices[0].message.content,\n"
        "        \"steps\": max_steps,\n"
        "        \"trace\": trace,\n"
        "        \"terminated_by\": \"max_steps\",\n"
        "    }"
    ),
    md(
        "## 6. Production v1 in action\n"
        "\n"
        "Run the same forced-loop case from §4 with the production loop. Now we get a **structured "
        "trace** (no print spam) and **parallel-tool-call safety**."
    ),
    code(
        "result = await run_agent(\n"
        "    \"Compute the sum of these numbers using add — one call at a time: 12345, 67890, 11111, 22222.\",\n"
        "    TOOLS,\n"
        "    EXECUTORS,\n"
        "    system=\"You are a calculator. Always use the add tool — do not compute in your head.\",\n"
        ")\n"
        "print(\"answer:\", result[\"answer\"])\n"
        "print(\"\\ntrace:\")\n"
        "for entry in result[\"trace\"]:\n"
        "    calls = entry['tool_calls'] or '—'\n"
        "    print(f\"  step {entry['step']}: tools={calls}  tokens={entry['tokens']}\")"
    ),
    md(
        "## 7. Parallel tool calls\n"
        "\n"
        "When the LLM has *independent* sub-questions it can issue multiple tool calls in a single "
        "turn. `parallel_tool_calls=True` lets that happen. Without it you'd get N round-trips for N "
        "independent calls.\n"
        "\n"
        "Watch the `tool_calls` column in the trace below — step 0 should show three calls."
    ),
    code(
        "result = await run_agent(\n"
        "    \"Compute 1+1, 2+2, and 3+3 — give me all three answers.\",\n"
        "    TOOLS,\n"
        "    EXECUTORS,\n"
        ")\n"
        "print(\"answer:\", result[\"answer\"])\n"
        "print(\"\\ntrace:\")\n"
        "for entry in result[\"trace\"]:\n"
        "    print(f\"  step {entry['step']}: {entry['tool_calls']}\")"
    ),
    md(
        "Step 0 should show `['add', 'add', 'add']` — three tool calls in one turn. Step 1 is the final answer.\n"
        "\n"
        "Without `parallel_tool_calls=True` you'd see three separate steps each with one call — three "
        "extra round-trips. On a 25-step research task this can save 30-40% on cost.\n"
    ),
    md(
        "## 8. Self-check\n"
        "\n"
        "1. Write `run_agent_v0` from memory. (Six core lines, ignore the print scaffolding.)\n"
        "2. Name three ways a model might NOT use a tool you registered. (Hint: §3 shows three trace shapes.)\n"
        "3. What does `tool_choice=\"none\"` guarantee about the next assistant message? When do we use it in `run_agent`?\n"
        "4. Why do we wrap tool execution in `try/except` and convert errors to observations — instead of letting them raise?\n"
        "5. In §3, the model bypassed the tool. In §4, it didn't. What was different about the prompt? Generalise the rule.\n"
        "6. **Partial-loop + late-bypass** — explain why this trace shape is more dangerous than full bypass. How would you detect it programmatically?\n"
        "7. **Non-determinism** — you run the same prompt twice and get different answers. Is the agent broken? What do you measure instead of \"does it work\"?\n"
        "\n"
        "## What's next\n"
        "\n"
        "Notebook **02** turns the loose `TOOLS` and `EXECUTORS` dicts into proper `BaseTool` and "
        "`ToolRegistry` classes — and digs into OpenAI's `strict: True` mode (the production must-have "
        "for preventing argument-shape hallucinations).\n"
    ),
]

write("notebooks/01_agent_loop.ipynb", cells)
print("wrote notebooks/01_agent_loop.ipynb")
