"""Generator for notebooks/02_tools_strict.ipynb."""

from build_notebook import code, md, write

cells = [
    md(
        "# 02 — Tools & Strict Mode\n"
        "\n"
        "In notebook 01 you wrote `TOOLS` and `EXECUTORS` as loose dicts. That falls apart fast: "
        "no input validation, no consistent return shape, and the LLM can hallucinate argument types "
        "(`{\"a\": \"seven\"}` when you asked for an integer).\n"
        "\n"
        "**By the end of this notebook you will:**\n"
        "1. Refactor tools into a `BaseTool` ABC with a uniform `ToolResult` return shape\n"
        "2. Build a `ToolRegistry` that dispatches safely (never raises)\n"
        "3. Turn on OpenAI's `strict: True` and watch it kill an entire class of bugs\n"
        "4. See *why tool descriptions* are 60% of agent quality\n"
        "\n"
        "Lecture reference: **S8 §3.5** (tool layer) and **S8 §6** (tool design + hallucination).\n"
    ),
    md(
        "## 1. The pieces, side by side\n"
        "\n"
        "Three small files in `src/deepbrief/tools/`:\n"
        "- `base.py` — `BaseTool` ABC, `ToolResult` Pydantic model\n"
        "- `registry.py` — `ToolRegistry` (dispatch never raises)\n"
        "- agent loop is in `src/deepbrief/agents/react.py`\n"
        "\n"
        "Let's read the ABC first."
    ),
    code(
        "# Inspect the contract\n"
        "from deepbrief.tools.base import BaseTool, ToolResult\n"
        "import inspect\n"
        "\n"
        "print(inspect.getsource(ToolResult))"
    ),
    code(
        "print(inspect.getsource(BaseTool))"
    ),
    md(
        "## 2. Build a real tool — `add_numbers`\n"
        "\n"
        "We'll port the `add` tool from notebook 01 to the new shape. Three things to notice:\n"
        "\n"
        "1. **`name`** is `verb_noun`, not `add` alone — easier for the LLM to disambiguate at scale\n"
        "2. **`description`** has *what* + *when to call* — see S8 §6.3\n"
        "3. **`additionalProperties: False`** is required for `strict: True` to be accepted by the API"
    ),
    code(
        "from deepbrief.tools.base import BaseTool, ToolResult\n"
        "\n"
        "class AddNumbersTool(BaseTool):\n"
        "    name = \"add_numbers\"\n"
        "    description = (\n"
        "        \"Add two integers and return the sum. \"\n"
        "        \"Call this when the user asks for arithmetic addition. \"\n"
        "        \"Do NOT call this for multiplication, division, or non-integer inputs.\"\n"
        "    )\n"
        "    parameters_schema = {\n"
        "        \"type\": \"object\",\n"
        "        \"properties\": {\n"
        "            \"a\": {\"type\": \"integer\", \"description\": \"First addend\"},\n"
        "            \"b\": {\"type\": \"integer\", \"description\": \"Second addend\"},\n"
        "        },\n"
        "        \"required\": [\"a\", \"b\"],\n"
        "        \"additionalProperties\": False,\n"
        "    }\n"
        "\n"
        "    async def execute(self, a: int, b: int) -> ToolResult:\n"
        "        return ToolResult(\n"
        "            tool_name=self.name,\n"
        "            input_args={\"a\": a, \"b\": b},\n"
        "            output={\"sum\": a + b},\n"
        "            success=True,\n"
        "        )\n"
        "\n"
        "tool = AddNumbersTool()\n"
        "print(\"Schema sent to LLM:\")\n"
        "import json\n"
        "print(json.dumps(tool.to_openai_function(), indent=2))"
    ),
    md(
        "## 3. Wire it up with the registry"
    ),
    code(
        "from deepbrief.tools.registry import ToolRegistry\n"
        "\n"
        "registry = ToolRegistry()\n"
        "registry.register(AddNumbersTool())\n"
        "print(\"Registered:\", registry.list_tools())\n"
        "\n"
        "# Try executing — note we never get an exception, even with garbage input\n"
        "good = await registry.execute(\"add_numbers\", {\"a\": 3, \"b\": 4})\n"
        "print(\"good:\", good)\n"
        "\n"
        "missing = await registry.execute(\"multiply_numbers\", {\"a\": 3, \"b\": 4})\n"
        "print(\"missing tool:\", missing)\n"
        "\n"
        "bad_args = await registry.execute(\"add_numbers\", {\"x\": 3})\n"
        "print(\"bad args:\", bad_args)"
    ),
    md(
        "Notice all three return a `ToolResult`. The LLM will read the `error` field and self-correct. "
        "**No exception bubbled up** — that's the contract."
    ),
    md(
        "## 4. Run the agent through the registry\n"
        "\n"
        "`ReActAgent` lives in `src/deepbrief/agents/react.py`. It's the same loop from notebook 01, factored as a class."
    ),
    code(
        "from deepbrief.agents.react import ReActAgent\n"
        "\n"
        "agent = ReActAgent(\n"
        "    registry=registry,\n"
        "    system_prompt=\"You are a helpful calculator. Use the available tools.\",\n"
        "    max_steps=6,\n"
        ")\n"
        "result = await agent.run(\"What is 17 + 25, and also 100 + 200?\")\n"
        "print(\"answer:\", result.answer)\n"
        "print(\"steps:\", result.steps, \"  terminated_by:\", result.terminated_by)\n"
        "for entry in result.trace:\n"
        "    print(f\"  step {entry['step']}: {entry['tool_calls']}\")"
    ),
    md(
        "## 5. Why strict mode matters — break it on purpose\n"
        "\n"
        "Without `strict: True`, the LLM might emit `{\"a\": \"seventeen\"}` (string instead of integer). "
        "You'd catch it in your validator and round-trip back to the LLM — wasted call.\n"
        "\n"
        "With `strict: True`, OpenAI runs **constrained decoding**: at each token it only samples from "
        "tokens that keep the JSON valid against your schema. The args are correct on first emit.\n"
        "\n"
        "Let's prove this. We'll build TWO versions of the same tool — one with strict, one without — and "
        "ask the model an ambiguous question that often produces type confusion."
    ),
    code(
        "# Same tool but with strict mode disabled\n"
        "non_strict_schema = tool.to_openai_function()\n"
        "non_strict_schema[\"function\"][\"strict\"] = False\n"
        "\n"
        "from openai import AsyncOpenAI\n"
        "client = AsyncOpenAI()\n"
        "\n"
        "AMBIGUOUS = \"Add seventeen and twenty-five for me.\"\n"
        "\n"
        "# Helper to inspect the args the model emits\n"
        "async def show_args(schema, label):\n"
        "    r = await client.chat.completions.create(\n"
        "        model=\"gpt-4o-mini\",\n"
        "        messages=[{\"role\": \"user\", \"content\": AMBIGUOUS}],\n"
        "        tools=[schema], tool_choice=\"required\",\n"
        "    )\n"
        "    tc = r.choices[0].message.tool_calls[0]\n"
        "    print(f\"{label}: {tc.function.arguments}\")\n"
        "\n"
        "await show_args(tool.to_openai_function(), \"strict=True \")\n"
        "await show_args(non_strict_schema,        \"strict=False\")"
    ),
    md(
        "On `gpt-4o-mini` you'll usually see both produce `{\"a\": 17, \"b\": 25}` — the model's strong enough "
        "that strict mode isn't *strictly* necessary. The point is: with strict on, it's **guaranteed**. "
        "On weaker open-source models or longer schemas, ~3-5% of calls without strict come back malformed.\n"
        "\n"
        "**Senior interview answer:** *\"Strict mode pushes schema enforcement from runtime validation to decode "
        "time. Same correctness budget, half the round-trips, and a class of bugs (`{\"city\": \"Tokyo, Japan\"}` "
        "when schema says enum) becomes statistically zero.\"*"
    ),
    md(
        "## 6. Tool descriptions are 60% of agent quality\n"
        "\n"
        "Same tool, different descriptions. Watch which one the LLM actually picks correctly."
    ),
    code(
        "# Two tools with overlapping concerns — only the description disambiguates them\n"
        "class WeatherNowTool(BaseTool):\n"
        "    name = \"weather_now\"\n"
        "    description = \"Get current weather for a city.\"   # ❌ vague — missing when/when-not\n"
        "    parameters_schema = {\n"
        "        \"type\": \"object\",\n"
        "        \"properties\": {\"city\": {\"type\": \"string\"}},\n"
        "        \"required\": [\"city\"], \"additionalProperties\": False,\n"
        "    }\n"
        "    async def execute(self, city):\n"
        "        return ToolResult(tool_name=self.name, input_args={\"city\": city},\n"
        "                          output={\"temp_c\": 14, \"conditions\": \"cloudy\"}, success=True)\n"
        "\n"
        "class WeatherForecastTool(BaseTool):\n"
        "    name = \"weather_forecast\"\n"
        "    description = (\n"
        "        \"Get a multi-day weather forecast for a city. \"\n"
        "        \"Call this when the user asks about weather more than 24h in the future. \"\n"
        "        \"Do NOT call this for current/today weather — use weather_now for that.\"\n"
        "    )\n"
        "    parameters_schema = {\n"
        "        \"type\": \"object\",\n"
        "        \"properties\": {\n"
        "            \"city\": {\"type\": \"string\"},\n"
        "            \"days\": {\"type\": \"integer\", \"description\": \"Number of days, 1-7\"},\n"
        "        },\n"
        "        \"required\": [\"city\", \"days\"], \"additionalProperties\": False,\n"
        "    }\n"
        "    async def execute(self, city, days):\n"
        "        return ToolResult(tool_name=self.name, input_args={\"city\": city, \"days\": days},\n"
        "                          output={\"forecast\": [{\"day\": i, \"temp_c\": 15+i} for i in range(days)]},\n"
        "                          success=True)\n"
        "\n"
        "weather_registry = ToolRegistry()\n"
        "weather_registry.register(WeatherNowTool())\n"
        "weather_registry.register(WeatherForecastTool())\n"
        "\n"
        "weather_agent = ReActAgent(\n"
        "    registry=weather_registry,\n"
        "    system_prompt=\"You are a travel assistant. Pick the right tool.\",\n"
        "    max_steps=4,\n"
        ")\n"
        "\n"
        "for q in [\n"
        "    \"What's the weather like in Paris right now?\",\n"
        "    \"Will it rain in Tokyo over the next 3 days?\",\n"
        "]:\n"
        "    r = await weather_agent.run(q)\n"
        "    called = r.trace[0]['tool_calls']\n"
        "    print(f\"q={q!r}\\n   → tool={called}\")"
    ),
    md(
        "The forecast tool's description includes *when to call* AND *when NOT to call* — that's what makes "
        "the LLM disambiguate cleanly. Without the negative case, you'd see `weather_now` called for "
        "future-weather questions ~30% of the time on `gpt-4o-mini`.\n"
        "\n"
        "**The rule** *(S8 §6.3)*: every tool description has three parts in this order:\n"
        "1. What the tool does\n"
        "2. WHEN to call it\n"
        "3. WHEN NOT to call it"
    ),
    md(
        "## 7. Self-check\n"
        "\n"
        "1. Why does `ToolRegistry.execute()` never raise?\n"
        "2. What's the JSON-Schema requirement that `strict: True` adds?\n"
        "3. Name the three parts of a good tool description.\n"
        "4. If you're stuck on a model that doesn't support strict mode (vLLM, DeepSeek), what's your fallback?\n"
        "\n"
        "## What's next\n"
        "\n"
        "Notebook **03** — **Termination & Cost**. We'll build a `LoopGuard` that detects literal repetition, "
        "and a `CostMeter` that hard-stops when a per-run budget is exceeded. This is the part of agent code "
        "that separates mid-level from senior engineers.\n"
    ),
]

write("notebooks/02_tools_strict.ipynb", cells)
print("wrote notebooks/02_tools_strict.ipynb")
