"""Generator for notebooks/04_fastmcp_server.ipynb."""

from build_notebook import code, md, write

cells = [
    md(
        "# 04 — Build Your First MCP Server (FastMCP)\n"
        "\n"
        "We've spent three notebooks on the *agent* side. Now we cross over to **MCP** — the protocol "
        "that standardises how agents talk to tools and data sources.\n"
        "\n"
        "**Mental model in one line:** MCP is the USB-C port for AI applications. Same plug shape on "
        "both ends, regardless of who built the AI app or who built the data source.\n"
        "\n"
        "**By the end of this notebook you will:**\n"
        "1. Build a working MCP server with **FastMCP** in ~50 lines\n"
        "2. Inspect it with the **MCP Inspector** (the `curl` of MCP development)\n"
        "3. Connect a Python client and run the full lifecycle (initialize → list_tools → call_tool)\n"
        "4. See the real JSON-RPC 2.0 traffic that flows under the hood\n"
    ),
    md(
        "## 1. Why FastMCP\n"
        "\n"
        "Before FastMCP, you'd hand-write JSON-RPC 2.0 message handlers, manage `tools/list` and "
        "`tools/call` dispatch, define schemas in JSON. With FastMCP:\n"
        "\n"
        "- A `@mcp.tool()` decorator on a Python function exposes it as a tool\n"
        "- Type hints (`title: str`) become the input JSON Schema\n"
        "- Docstring becomes the tool description\n"
        "- Args section in the docstring becomes per-parameter descriptions\n"
        "- The lifecycle messages (`initialize`, `tools/list`, etc.) are auto-generated\n"
        "\n"
        "FastMCP started as a standalone library and was absorbed into the official `mcp` Python SDK. "
        "We use the SDK-bundled version: `from mcp.server.fastmcp import FastMCP`.\n"
    ),
    md(
        "## 2. The notes server\n"
        "\n"
        "Lives at `src/deepbrief/mcp_servers/notes_server.py`. It exposes four tools for the research "
        "agent to persist findings during a brief.\n"
        "\n"
        "Read it first."
    ),
    code(
        "import inspect\n"
        "from deepbrief.mcp_servers import notes_server\n"
        "\n"
        "# Show just the top of the file plus the four tool functions\n"
        "src = inspect.getsource(notes_server)\n"
        "print(src[:1200])\n"
        "print(\"... [docstrings + tool bodies — see file] ...\")"
    ),
    md(
        "## 3. What FastMCP auto-generates\n"
        "\n"
        "For each `@mcp.tool()` function FastMCP introspects:\n"
        "- Function name → tool name\n"
        "- Type hints → JSON Schema for `inputSchema`\n"
        "- Docstring summary → tool description\n"
        "- Docstring `Args:` block → per-parameter `description`\n"
        "\n"
        "Let's verify by listing what the FastMCP instance would expose."
    ),
    code(
        "# FastMCP keeps its registered tools internally; we can ask the SDK for the list\n"
        "tools = await notes_server.mcp.list_tools()\n"
        "for t in tools:\n"
        "    print(f\"• {t.name}\")\n"
        "    print(f\"  description: {(t.description or '').splitlines()[0]}\")\n"
        "    print(f\"  schema:      {t.inputSchema}\")\n"
        "    print()"
    ),
    md(
        "Notice the schemas have proper types and descriptions — all from your Python type hints + docstring. "
        "No JSON-Schema-by-hand. This is the FastMCP win.\n"
    ),
    md(
        "## 4. Run it as a real subprocess and connect a client\n"
        "\n"
        "Now we'll launch the server as a *subprocess* (stdio transport) and connect from Python. This "
        "is exactly how Claude Desktop and Cursor talk to MCP servers when the server lives on the same "
        "machine.\n"
        "\n"
        "We use the official MCP SDK's `stdio_client` + `ClientSession`."
    ),
    code(
        "import sys\n"
        "from mcp import ClientSession, StdioServerParameters\n"
        "from mcp.client.stdio import stdio_client\n"
        "\n"
        "# Tell the SDK how to spawn our server\n"
        "server_params = StdioServerParameters(\n"
        "    command=sys.executable,\n"
        "    args=[\"-m\", \"deepbrief.mcp_servers.notes_server\"],   # stdio default\n"
        ")\n"
        "\n"
        "# Open the transport, then the session — both are async context managers\n"
        "async with stdio_client(server_params) as (read, write):\n"
        "    async with ClientSession(read, write) as session:\n"
        "        # PHASE 1: handshake — capability negotiation happens here\n"
        "        init_result = await session.initialize()\n"
        "        print(f\"Connected to: {init_result.serverInfo.name} v{init_result.serverInfo.version}\")\n"
        "        print(f\"Server capabilities: {init_result.capabilities}\\n\")\n"
        "\n"
        "        # PHASE 2: discovery\n"
        "        tools = (await session.list_tools()).tools\n"
        "        print(f\"Tools advertised by server ({len(tools)}):\")\n"
        "        for t in tools:\n"
        "            print(f\"  • {t.name}\")\n"
        "\n"
        "        # PHASE 3: invocation\n"
        "        save_result = await session.call_tool(\n"
        "            \"save_note\",\n"
        "            {\"title\": \"WebGPU support\", \"content\": \"Stable in Chrome 121+ ([source](https://...))\"},\n"
        "        )\n"
        "        print(f\"\\nsave_note → {save_result.content[0].text}\")\n"
        "\n"
        "        list_result = await session.call_tool(\"list_notes\", {})\n"
        "        print(f\"list_notes → {list_result.content[0].text}\")"
    ),
    md(
        "What happened on the wire:\n"
        "\n"
        "```jsonc\n"
        "// 1. We sent (over stdin):\n"
        "{ \"jsonrpc\": \"2.0\", \"id\": 1, \"method\": \"initialize\",\n"
        "  \"params\": { \"protocolVersion\": \"2025-11-25\", \"capabilities\": {...}, \"clientInfo\": {...} } }\n"
        "\n"
        "// 2. Server replied (over stdout):\n"
        "{ \"jsonrpc\": \"2.0\", \"id\": 1,\n"
        "  \"result\": { \"protocolVersion\": \"2025-11-25\", \"capabilities\": {...},\n"
        "               \"serverInfo\": { \"name\": \"deepbrief-notes\", \"version\": \"...\" } } }\n"
        "\n"
        "// 3. We sent the initialized notification, then list_tools, then call_tool — same pattern.\n"
        "```\n"
        "\n"
        "FastMCP wrote all that for you. You wrote four Python functions.\n"
    ),
    md(
        "## 5. Debug with the MCP Inspector (the `curl` of MCP)\n"
        "\n"
        "When something doesn't work, you don't want to `print()` your way through async transport code. "
        "You want a **GUI** that shows you the exact JSON-RPC traffic and lets you call `tools/list` and "
        "`tools/call` by hand.\n"
        "\n"
        "That's the MCP Inspector. Run this in a terminal (NOT in the notebook):\n"
        "\n"
        "```bash\n"
        "npx @modelcontextprotocol/inspector python -m deepbrief.mcp_servers.notes_server\n"
        "```\n"
        "\n"
        "It opens **http://localhost:6274** with:\n"
        "- A **History** tab — every JSON-RPC request and response\n"
        "- A **Tools** tab — list + call buttons (auto-renders forms from your schemas)\n"
        "- A **Resources** / **Prompts** tab — empty in our case (we only expose tools)\n"
        "\n"
        "Try this drill:\n"
        "\n"
        "1. Click **Connect**\n"
        "2. **Tools** tab → **List Tools** → you should see `save_note`, `list_notes`, `read_note`, `delete_note`\n"
        "3. Click `save_note` → fill `title` and `content` → **Run Tool**\n"
        "4. Click `list_notes` → **Run Tool** → see your note\n"
        "5. Open the **History** tab and verify each call sent valid JSON-RPC 2.0\n"
        "\n"
        "Source: official inspector tool — `npm i -g @modelcontextprotocol/inspector` for permanent install."
    ),
    md(
        "## 6. Why we exposed *tools*, not *resources* or *prompts*\n"
        "\n"
        "MCP servers can expose three primitives:\n"
        "\n"
        "| Primitive | REST analogy | Who controls it |\n"
        "|---|---|---|\n"
        "| **Tools** | `POST` — has side effects, may compute | **Model-controlled** |\n"
        "| **Resources** | `GET` — read-only | **Application-controlled** |\n"
        "| **Prompts** | reusable templates | **User-controlled** |\n"
        "\n"
        "We used tools for everything because the LLM needs to *decide* when to save and read notes. "
        "If we wanted to expose, say, *all existing notes* as read-only context the host can prefetch, "
        "we'd register them as resources. We don't need that yet.\n"
        "\n"
        "**Practical rule:** start with tools. Add resources only when you have read-only state the host "
        "should prefetch. Add prompts only if your host has a slash-command UI (Claude Desktop does)."
    ),
    md(
        "## 7. Self-check\n"
        "\n"
        "1. What does FastMCP generate from a Python function's type hints? From its docstring?\n"
        "2. What are the three protocol phases an MCP client goes through after connecting?\n"
        "3. Why is the **MCP Inspector** the equivalent of `curl` for MCP development?\n"
        "4. Name the three primitives an MCP server can expose, and who controls invocation of each.\n"
        "\n"
        "## What's next\n"
        "\n"
        "Notebook **05** — same server, **change one line** to expose it as Streamable HTTP. We'll explore "
        "stdio vs HTTP transports, why Plain SSE was deprecated in 2025, and the `Mcp-Session-Id` header."
    ),
]

write("notebooks/04_fastmcp_server.ipynb", cells)
print("wrote notebooks/04_fastmcp_server.ipynb")
