"""Generator for notebooks/05_mcp_transports.ipynb."""

from build_notebook import code, md, write

cells = [
    md(
        "# 05 — MCP Transports: stdio vs Streamable HTTP\n"
        "\n"
        "MCP is a **two-layer protocol**:\n"
        "- **Data layer** — JSON-RPC 2.0 messages (what they mean)\n"
        "- **Transport layer** — how those messages move (the bytes on the wire)\n"
        "\n"
        "Same data layer works over stdio (local subprocess) or Streamable HTTP (remote service). "
        "This is the same idea as ASGI vs WSGI in Python web frameworks — protocol semantics live "
        "above transport.\n"
        "\n"
        "**By the end of this notebook you will:**\n"
        "1. Run the same `notes_server` over **both** transports\n"
        "2. See the `Mcp-Session-Id` header that makes Streamable HTTP stateful\n"
        "3. Build a second MCP server (`cache_server`) and connect to it remotely\n"
        "4. Pick the right transport for a given deployment\n"
    ),
    md(
        "## 1. The decision table\n"
        "\n"
        "| Factor | Choose **stdio** | Choose **Streamable HTTP** |\n"
        "|---|---|---|\n"
        "| Server location | Same machine as host | Different machine / cloud |\n"
        "| Auth | Implicit (process owner) | OAuth 2.1 / API key (mandated for public servers per Nov 2025 spec) |\n"
        "| Multi-tenancy | One server per host process | One server, many concurrent clients |\n"
        "| Network ops | None | Reverse proxy, TLS, rate limiting available |\n"
        "| Cold start | ~50-100 ms (process spawn) | ~250-600 ms (Python SDK), then warm |\n"
        "| Best fit | IDE plugins, desktop apps, dev tools | Enterprise SaaS, multi-user agents, your VoyageAI-style deployment |\n"
    ),
    md(
        "## 2. Same server, two transports — change one line\n"
        "\n"
        "Look at the bottom of `notes_server.py`:\n"
        "\n"
        "```python\n"
        "if \"--http\" in sys.argv:\n"
        "    mcp.settings.host = \"0.0.0.0\"; mcp.settings.port = 8765\n"
        "    mcp.run(transport=\"streamable-http\")\n"
        "else:\n"
        "    mcp.run()  # stdio\n"
        "```\n"
        "\n"
        "Same `@mcp.tool()` decorators. Same business logic. Just a different `transport=` argument. **Protocol decoupled from transport.**\n"
    ),
    md(
        "## 3. Run notes_server as HTTP (in a background subprocess)"
    ),
    code(
        "import os\n"
        "import subprocess\n"
        "import sys\n"
        "import time\n"
        "\n"
        "# Kill any leftover from a previous run of this cell\n"
        "subprocess.run([\"pkill\", \"-f\", \"deepbrief.mcp_servers.notes_server\"], capture_output=True)\n"
        "\n"
        "notes_proc = subprocess.Popen(\n"
        "    [sys.executable, \"-m\", \"deepbrief.mcp_servers.notes_server\", \"--http\"],\n"
        "    stdout=subprocess.PIPE, stderr=subprocess.PIPE,\n"
        "    env={**os.environ, \"MCP_PORT\": \"8766\"},\n"
        ")\n"
        "time.sleep(2)   # give it a moment to bind the port\n"
        "print(f\"notes_server pid={notes_proc.pid}  url=http://localhost:8766/mcp\")\n"
        "print(\"Status:\", \"running\" if notes_proc.poll() is None else f\"DEAD (exit {notes_proc.returncode})\")"
    ),
    md(
        "## 4. Connect via Streamable HTTP\n"
        "\n"
        "Note the difference from notebook 04: instead of `stdio_client(server_params)`, we use "
        "`streamablehttp_client(url=...)`. Everything else (initialize, list_tools, call_tool) is identical."
    ),
    code(
        "from mcp import ClientSession\n"
        "from mcp.client.streamable_http import streamablehttp_client\n"
        "\n"
        "async with streamablehttp_client(url=\"http://localhost:8766/mcp\") as (read, write, _):\n"
        "    async with ClientSession(read, write) as session:\n"
        "        init = await session.initialize()\n"
        "        print(f\"Connected via HTTP: {init.serverInfo.name}\\n\")\n"
        "\n"
        "        tools = (await session.list_tools()).tools\n"
        "        print(f\"Tools ({len(tools)}):\", [t.name for t in tools])\n"
        "\n"
        "        # Save a note\n"
        "        save = await session.call_tool(\n"
        "            \"save_note\",\n"
        "            {\"title\": \"Saved via HTTP\", \"content\": \"Same server, different transport.\"},\n"
        "        )\n"
        "        print(f\"\\nsave_note → {save.content[0].text}\")\n"
        "\n"
        "        # List notes — should include the one we just saved AND notes from notebook 04\n"
        "        listing = await session.call_tool(\"list_notes\", {})\n"
        "        print(f\"\\nlist_notes → {listing.content[0].text}\")"
    ),
    md(
        "## 5. The wire-level difference\n"
        "\n"
        "Same JSON-RPC 2.0 messages, different envelope:\n"
        "\n"
        "```\n"
        "stdio:                              Streamable HTTP:\n"
        "→  {\"jsonrpc\":\"2.0\",                 →  POST /mcp HTTP/1.1\n"
        "    \"method\":\"initialize\",...}          Mcp-Session-Id: <not yet>\n"
        "                                         Content-Type: application/json\n"
        "                                         {\"jsonrpc\":\"2.0\",\"method\":\"initialize\",...}\n"
        "                                     ←  HTTP/1.1 200 OK\n"
        "                                         Mcp-Session-Id: 8b7e3...   ← assigned by server\n"
        "                                         {\"jsonrpc\":\"2.0\",\"result\":{...}}\n"
        "                                     →  POST /mcp\n"
        "                                         Mcp-Session-Id: 8b7e3...   ← echo it back on every call\n"
        "                                         {\"jsonrpc\":\"2.0\",\"method\":\"tools/list\",...}\n"
        "```\n"
        "\n"
        "**Key design decision:** one endpoint (`POST /mcp`), two interaction modes.\n"
        "- Simple request → JSON response (works with any HTTP infra: CDN, ALB, reverse proxy)\n"
        "- Long-running tool → upgrade response to **Server-Sent Events** for streaming progress\n"
        "\n"
        "**Sessions** are identified by the `Mcp-Session-Id` header. Stateful, but unlike WebSocket the "
        "session can survive transient disconnects — clients reconnect with the same id.\n"
        "\n"
        "**Why not plain SSE?** The original 2024-11-05 spec used `/sse` (server→client) + `/messages` "
        "(client→server). Deprecated 2025-03-26 because: two endpoints annoyed ALB/CDN config, connection "
        "drops meant full session loss, firewalls broke long-lived SSE streams. Streamable HTTP is the "
        "current standard."
    ),
    md(
        "## 6. Build a second server: `cache_server`\n"
        "\n"
        "We'll need this in notebook 06 for the agent to dedupe web fetches. It's HTTP-only by design — "
        "models the *remote shared service* pattern.\n"
        "\n"
        "Read it briefly:"
    ),
    code(
        "import inspect\n"
        "from deepbrief.mcp_servers import cache_server\n"
        "\n"
        "src = inspect.getsource(cache_server)\n"
        "print(src[:1500])\n"
        "print(\"...\\n\")\n"
        "print(\"  ↑ Pattern is exactly the same as notes_server. \")\n"
        "print(\"    What changes: in-memory dict instead of files, HTTP-only.\")"
    ),
    md(
        "## 7. Run cache_server and connect"
    ),
    code(
        "subprocess.run([\"pkill\", \"-f\", \"deepbrief.mcp_servers.cache_server\"], capture_output=True)\n"
        "\n"
        "cache_proc = subprocess.Popen(\n"
        "    [sys.executable, \"-m\", \"deepbrief.mcp_servers.cache_server\"],\n"
        "    stdout=subprocess.PIPE, stderr=subprocess.PIPE,\n"
        "    env={**os.environ, \"PORT\": \"8765\"},\n"
        ")\n"
        "time.sleep(2)\n"
        "print(f\"cache_server pid={cache_proc.pid}  url=http://localhost:8765/mcp\")"
    ),
    code(
        "async with streamablehttp_client(url=\"http://localhost:8765/mcp\") as (read, write, _):\n"
        "    async with ClientSession(read, write) as session:\n"
        "        await session.initialize()\n"
        "\n"
        "        # Miss\n"
        "        r = await session.call_tool(\"cache_get\", {\"key\": \"https://example.com\"})\n"
        "        print(\"miss:  \", r.content[0].text)\n"
        "\n"
        "        # Set\n"
        "        r = await session.call_tool(\"cache_set\",\n"
        "            {\"key\": \"https://example.com\", \"value\": \"hello world\"})\n"
        "        print(\"set:   \", r.content[0].text)\n"
        "\n"
        "        # Hit\n"
        "        r = await session.call_tool(\"cache_get\", {\"key\": \"https://example.com\"})\n"
        "        print(\"hit:   \", r.content[0].text)\n"
        "\n"
        "        # Stats\n"
        "        r = await session.call_tool(\"cache_stats\", {})\n"
        "        print(\"stats: \", r.content[0].text)"
    ),
    md(
        "## 8. Cleanup — kill the background servers"
    ),
    code(
        "for proc, name in [(notes_proc, \"notes\"), (cache_proc, \"cache\")]:\n"
        "    proc.terminate()\n"
        "    try:\n"
        "        proc.wait(timeout=5)\n"
        "        print(f\"{name}_server stopped\")\n"
        "    except subprocess.TimeoutExpired:\n"
        "        proc.kill()\n"
        "        print(f\"{name}_server force-killed\")"
    ),
    md(
        "## 9. The \"wrap stdio as HTTP\" pattern\n"
        "\n"
        "Sometimes a server you want to use ships **only** stdio (most early MCP servers were stdio-only). "
        "But your agent runs in a Kubernetes pod and can't subprocess-spawn things. The fix is a **gateway** "
        "that runs the stdio server inside it and exposes Streamable HTTP outward.\n"
        "\n"
        "Cloudflare's `supergateway`, `mcp-remote`, and the open-source **Bifrost** gateway all do this. We "
        "won't build one in this lab, but knowing the pattern exists is a senior signal."
    ),
    md(
        "## 10. Self-check\n"
        "\n"
        "1. Same `@mcp.tool()` business logic. What changed to swap stdio → HTTP?\n"
        "2. What does the `Mcp-Session-Id` header buy you over a plain WebSocket connection?\n"
        "3. Why was the original Plain SSE transport deprecated in 2025?\n"
        "4. Your team picked an MCP server that only ships stdio. Your agent runs in EKS. How do you bridge it?\n"
        "\n"
        "## What's next\n"
        "\n"
        "Notebook **06** — wire MCP tools into the agent's `ToolRegistry` via an adapter. After this notebook "
        "the agent doesn't know whether a tool is local Python, an HTTP MCP server, or a stdio MCP server — "
        "they all look the same to the loop."
    ),
]

write("notebooks/05_mcp_transports.ipynb", cells)
print("wrote notebooks/05_mcp_transports.ipynb")
