"""Generator for notebooks/07b_langgraph_rewrite.ipynb."""

from build_notebook import code, md, write

cells = [
    md(
        "# 07b — LangGraph Rewrite: Same Deep Research, Different Runtime\n"
        "\n"
        "In notebook **07** we built deep research as a hand-rolled multi-agent system: "
        "a `Coordinator` Python class, two `Researcher` agents running as FastAPI subprocesses, "
        "JSON-RPC A2A calls between them, `asyncio.gather` for parallel fan-out. **It worked.** "
        "It also exposed four pain points that LangGraph is built to fix.\n"
        "\n"
        "**By the end of this notebook you will:**\n"
        "1. Re-implement the **same** decompose → parallel-research → synthesize pipeline as a `StateGraph`\n"
        "2. Use the **`Send` API** for dynamic fan-out (sub-question count varies per run)\n"
        "3. Hit and fix the **#1 LangGraph beginner gotcha** — silent data loss in parallel branches without a reducer\n"
        "4. Inspect the graph's **state history** for free — preview of time-travel debugging (full coverage in 08)\n"
        "\n"
        "Lecture references: **S9 §2** (LangGraph mental model), **S9 §3.3** (time travel preview).\n"
        "\n"
        "**What this notebook does NOT add yet:**\n"
        "- `SqliteSaver` checkpointer (notebook 08)\n"
        "- `interrupt()` for HITL (notebook 08)\n"
        "- Worker pipeline / queue / SSE (notebook 09)\n"
        "\n"
        "We focus on the **orchestration pattern** itself.\n"
    ),
    md(
        "## 1. The four pain points from notebook 07\n"
        "\n"
        "Be honest about what hurt in the hand-rolled version. These are the same things every "
        "team feels when they outgrow `asyncio.gather`:\n"
        "\n"
        "| Pain | Hand-rolled (07) | LangGraph (07b) |\n"
        "|---|---|---|\n"
        "| State is scattered across local vars in `Coordinator.run` | every method passes args by hand | one `TypedDict` carries everything |\n"
        "| Parallel branch failures cascade messily | one researcher dying corrupts the gather | superstep barrier; failed branches replay in isolation |\n"
        "| No checkpoint — restart = lose all work | hard exit anywhere = start over | checkpointer adds full resumability (notebook 08) |\n"
        "| Hand-written `asyncio.gather` for fan-out | works but you write it every time | `Send` API + reducer = production-grade map-reduce |\n"
        "\n"
        "Lecture S9 calls this *\"the four-line argument for LangGraph in production: a state machine, "
        "durable across crashes, with HITL gates, fully auditable. Building these four pieces by hand on top "
        "of a hand-rolled agent loop is months of work.\"*\n"
        "\n"
        "Let's see the same pipeline run on LangGraph.\n"
    ),
    md(
        "## 2. Setup"
    ),
    code(
        "import asyncio\n"
        "import os\n"
        "from dotenv import load_dotenv\n"
        "\n"
        "load_dotenv()\n"
        "assert os.getenv(\"OPENAI_API_KEY\"), \"Set OPENAI_API_KEY in .env\"\n"
        "MODEL = os.getenv(\"OPENAI_MODEL\", \"gpt-4o-mini\")\n"
        "print(f\"Using model: {MODEL}\")\n"
        "print(\"Tavily configured:\", bool(os.getenv(\"TAVILY_API_KEY\")))"
    ),
    md(
        "## 3. The state object — TypedDict + reducers\n"
        "\n"
        "**State design is the most important architectural decision in a LangGraph system.** "
        "Too narrow and nodes pass data out-of-band. Too wide and you have an unmanageable blob.\n"
        "\n"
        "Our state has four fields and three writer patterns:"
    ),
    code(
        "import inspect\n"
        "from deepbrief.agents.langgraph_brief import ResearchState, Finding\n"
        "\n"
        "print(inspect.getsource(Finding))\n"
        "print(inspect.getsource(ResearchState))"
    ),
    md(
        "The interesting line is:\n"
        "\n"
        "```python\n"
        "findings: Annotated[list[Finding], operator.add]\n"
        "```\n"
        "\n"
        "Without that `Annotated[..., operator.add]` syntax, the field uses the **default reducer = overwrite**. "
        "If three parallel `research` nodes all return `{\"findings\": [...]}`, only one wins — and **which one wins "
        "depends on completion order**. That's non-deterministic silent data loss.\n"
        "\n"
        "With `operator.add`, the three lists CONCAT. All findings preserved.\n"
        "\n"
        "**Let me prove the bug exists.**"
    ),
    md(
        "## 4. The reducer bug, demonstrated\n"
        "\n"
        "I'm going to define **two** states — one without a reducer (default overwrite), one with — "
        "and build a tiny graph where three parallel nodes each contribute a finding."
    ),
    code(
        "import operator\n"
        "from typing import Annotated, TypedDict\n"
        "from langgraph.graph import END, START, StateGraph\n"
        "from langgraph.types import Send\n"
        "\n"
        "# ─── version A: NO reducer (the bug) ─────────────────────────────────\n"
        "class StateBuggy(TypedDict):\n"
        "    items: list[str]   # default reducer = overwrite\n"
        "\n"
        "def buggy_fanout(s):\n"
        "    return [Send(\"worker\", {\"i\": i}) for i in range(3)]\n"
        "\n"
        "def buggy_worker(payload):\n"
        "    return {\"items\": [f\"finding_{payload['i']}\"]}\n"
        "\n"
        "g_buggy = StateGraph(StateBuggy)\n"
        "g_buggy.add_node(\"start\", lambda s: {\"items\": []})\n"
        "g_buggy.add_node(\"worker\", buggy_worker)\n"
        "g_buggy.add_edge(START, \"start\")\n"
        "g_buggy.add_conditional_edges(\"start\", buggy_fanout, [\"worker\"])\n"
        "g_buggy.add_edge(\"worker\", END)\n"
        "\n"
        "buggy_app = g_buggy.compile()\n"
        "buggy_result = await buggy_app.ainvoke({\"items\": []})\n"
        "print(\"WITHOUT reducer:\", buggy_result)\n"
        "print(\"  → expected 3 items, got\", len(buggy_result[\"items\"]))"
    ),
    code(
        "# ─── version B: WITH reducer (the fix) ───────────────────────────────\n"
        "class StateFixed(TypedDict):\n"
        "    items: Annotated[list[str], operator.add]\n"
        "\n"
        "g_fixed = StateGraph(StateFixed)\n"
        "g_fixed.add_node(\"start\", lambda s: {\"items\": []})\n"
        "g_fixed.add_node(\"worker\", buggy_worker)\n"
        "g_fixed.add_edge(START, \"start\")\n"
        "g_fixed.add_conditional_edges(\"start\", buggy_fanout, [\"worker\"])\n"
        "g_fixed.add_edge(\"worker\", END)\n"
        "\n"
        "fixed_app = g_fixed.compile()\n"
        "fixed_result = await fixed_app.ainvoke({\"items\": []})\n"
        "print(\"WITH reducer:   \", fixed_result)\n"
        "print(\"  → expected 3 items, got\", len(fixed_result[\"items\"]))"
    ),
    md(
        "**This is the gotcha**. The buggy version loses two of the three findings. The fix is one line — "
        "wrap the type with `Annotated[..., reducer]`.\n"
        "\n"
        "**Senior interview answer** (S9 §2.3): *\"In a multi-agent LangGraph system, what happens if two "
        "parallel branches both modify the same state field with no reducer? The second write silently clobbers "
        "the first. Default reducer is overwrite. Declare `Annotated[list, operator.add]` for accumulators, "
        "`add_messages` for conversation history, or a custom function for dedup-aware merge.\"*\n"
    ),
    md(
        "## 5. The nodes\n"
        "\n"
        "Three nodes. Each is a pure function — read state, return a partial update dict.\n"
        "\n"
        "Notable: `research_node` doesn't take the full state — it takes a `Send` payload (just one "
        "sub-question). That's how dynamic fan-out broadcasts different work to each branch."
    ),
    code(
        "from deepbrief.agents.langgraph_brief import (\n"
        "    decompose_node, plan_research, research_node, synthesize_node,\n"
        ")\n"
        "for fn in [decompose_node, plan_research, research_node, synthesize_node]:\n"
        "    src = inspect.getsource(fn)\n"
        "    print(\"─\" * 60)\n"
        "    print(src.split('\\\"\\\"\\\"')[0].strip() + \"\\n    ...\")"
    ),
    md(
        "## 6. Build the graph\n"
        "\n"
        "Wire the four structural primitives:\n"
        "\n"
        "1. **`add_node`** — register the three pure functions.\n"
        "2. **`add_edge(START, ...)`** — entry point.\n"
        "3. **`add_conditional_edges(decompose, plan_research, [\"research\"])`** — `plan_research` returns "
        "`list[Send]`, NOT a string. LangGraph detects this and dispatches each Send as its own parallel branch.\n"
        "4. **`add_edge(\"research\", \"synthesize\")`** — static edge. The synthesize barrier waits for ALL "
        "parallel research branches to complete.\n"
    ),
    code(
        "from deepbrief.agents.langgraph_brief import build_brief_graph, build_brief_app\n"
        "\n"
        "graph = build_brief_graph()\n"
        "print(\"Nodes:\", list(graph.nodes))\n"
        "print(\"Static edges:\")\n"
        "for e in graph.edges:\n"
        "    print(f\"  {e[0]} → {e[1]}\")\n"
        "\n"
        "app = build_brief_app()\n"
        "print(\"\\nGraph compiled.\")"
    ),
    md(
        "## 7. Visualise the graph (optional but worth doing)\n"
        "\n"
        "LangGraph can render the compiled graph as a Mermaid diagram. Useful for documentation, "
        "useful for catching topology bugs — if the diagram doesn't match your mental model, your "
        "graph is wrong."
    ),
    code(
        "try:\n"
        "    from IPython.display import Image, display\n"
        "    display(Image(app.get_graph().draw_mermaid_png()))\n"
        "except Exception as e:\n"
        "    # PNG render needs `pyppeteer` or a remote service; fall back to ASCII\n"
        "    print(\"PNG render skipped:\", e)\n"
        "    print()\n"
        "    print(app.get_graph().draw_ascii())"
    ),
    md(
        "## 8. Run it\n"
        "\n"
        "Same input as notebook 07. Watch what happens.\n"
        "\n"
        "(This is a real LLM + web search call — takes 30-60s end to end.)"
    ),
    code(
        "TOPIC = \"State of the Model Context Protocol (MCP) in 2026\"\n"
        "\n"
        "result = await app.ainvoke({\"topic\": TOPIC, \"sub_questions\": [], \"findings\": [], \"draft\": None})\n"
        "\n"
        "print(\"=== SUB-QUESTIONS ===\")\n"
        "for i, q in enumerate(result[\"sub_questions\"], 1):\n"
        "    print(f\"{i}. {q}\")\n"
        "\n"
        "print(f\"\\n=== {len(result['findings'])} FINDINGS (one per researcher) ===\")\n"
        "for i, f in enumerate(result[\"findings\"], 1):\n"
        "    print(f\"\\n--- finding {i}: {f['question']} ---\")\n"
        "    print(f[\"summary\"][:300] + (\"...\" if len(f[\"summary\"]) > 300 else \"\"))\n"
        "    print(\"sources:\", f[\"sources\"][:2])\n"
        "\n"
        "print(\"\\n=== SYNTHESIZED BRIEF ===\")\n"
        "print(result[\"draft\"])"
    ),
    md(
        "**What just happened, in superstep terms** (S9 §2.6):\n"
        "\n"
        "- **Superstep 1**: `decompose` ran alone. 1 LLM call. Wrote `sub_questions` to state.\n"
        "- **Superstep 2**: `plan_research` returned N `Send` objects → **N `research` nodes ran in parallel** "
        "in the same superstep. Each made its own LLM + tool calls. All N completed before the barrier.\n"
        "- **Superstep 3**: `synthesize` ran alone, reading the now-aggregated `findings` list. 1 LLM call.\n"
        "\n"
        "If a researcher had crashed in superstep 2, the others' results would have been persisted as "
        "**pending writes** — on retry, only the failed researcher would replay, not all of them. That's "
        "the all-or-nothing superstep trap (S9 §2.6) working in your favor when paired with a checkpointer.\n"
    ),
    md(
        "## 9. Inspect the execution as a stream of typed events\n"
        "\n"
        "`app.astream_events()` exposes every node start/end/error as a typed event. This is what "
        "you wire into your UI for live progress bars and what notebook 09 will plumb into SSE."
    ),
    code(
        "event_counts = {}\n"
        "async for ev in app.astream_events(\n"
        "    {\"topic\": \"What is the A2A protocol?\", \"sub_questions\": [], \"findings\": [], \"draft\": None},\n"
        "    version=\"v2\",\n"
        "):\n"
        "    kind = ev[\"event\"]\n"
        "    event_counts[kind] = event_counts.get(kind, 0) + 1\n"
        "\n"
        "print(\"Event types observed in one full run:\")\n"
        "for kind, n in sorted(event_counts.items(), key=lambda x: -x[1]):\n"
        "    print(f\"  {n:3d}  {kind}\")"
    ),
    md(
        "Notice the volume of `on_chat_model_*` events — each LLM call inside each ReAct loop inside each "
        "researcher emits start/stream/end events. **You get full LLM-level observability without writing "
        "a single trace.append() call** — this is the LangGraph value-add over the hand-rolled S8 loop.\n"
    ),
    md(
        "## 10. Preview: state history (full coverage in notebook 08)\n"
        "\n"
        "Without a checkpointer, `app.get_state_history(config)` returns nothing — there's no durable state. "
        "But once we add `SqliteSaver` in notebook 08, the same API gives us **every superstep's state** "
        "as an inspectable snapshot.\n"
        "\n"
        "This is how you answer the senior interview question:\n"
        "\n"
        "> *\"A user reports the agent gave a different answer this time for the same query. Walk me through "
        "how you'd reproduce.\"*\n"
        "\n"
        "Answer: pull `get_state_history(thread_id)`, find the divergence point — usually a tool call that "
        "returned different data — replay or fork from that checkpoint. Without a checkpointer you'd be "
        "reading logs and guessing.\n"
        "\n"
        "We do the full reproduce-and-fork demo in notebook 08 once the checkpointer is wired in.\n"
    ),
    md(
        "## 11. Side-by-side: hand-rolled vs LangGraph\n"
        "\n"
        "Same problem, two implementations. The diff that matters:\n"
        "\n"
        "| Dimension | `coordinator.py` (notebook 07) | `langgraph_brief.py` (this notebook) |\n"
        "|---|---|---|\n"
        "| Lines of code | ~110 + ~100 in `a2a/` server/client | ~150 total |\n"
        "| Parallel safety | `asyncio.gather` with try/except per task | `operator.add` reducer — declared once |\n"
        "| State management | passed as method args + local vars | one `TypedDict` |\n"
        "| Error isolation | a researcher crash poisons `gather` | failed branch replays alone |\n"
        "| Topology visualization | none (read the code) | `draw_mermaid_png()` for free |\n"
        "| Event stream | hand-write trace.append() | `astream_events()` for free |\n"
        "| Add HITL gate | implement an approval table from scratch | add `interrupt()` in one node (notebook 08) |\n"
        "| Add checkpointing | implement state serializer + restore logic | `SqliteSaver()` one line (notebook 08) |\n"
        "\n"
        "**The line count is comparable. The capabilities are not.** Hand-rolled stops at \"it runs.\" "
        "LangGraph gets resumability, observability, HITL, and time-travel for free as you opt into them.\n"
    ),
    md(
        "## 12. When NOT to use LangGraph\n"
        "\n"
        "Honesty check (S9 §6):\n"
        "\n"
        "- **Pipeline-shaped task** — same exact steps every time → use a plain Python function with "
        "`asyncio.gather`. No `StateGraph`. \n"
        "- **Single strong agent suffices** — 3 specialists that are all `gpt-4o-mini` with slightly "
        "different prompts ≠ specialization. One Sonnet 4.6 with strict mode + good prompt + cost cap "
        "matches that on tightly-coupled tasks.\n"
        "- **Compliance / regulated** — auditors need determinism. Use a deterministic workflow with "
        "one or two clearly-bounded LLM steps.\n"
        "\n"
        "**Three checks before reaching for orchestration:**\n"
        "1. Does the task path vary meaningfully by input? If no, **pipeline.**\n"
        "2. Do you genuinely need multiple specialties? If no, **single agent.**\n"
        "3. Does input volume × token cost justify the 4-15× multiplier? If no, **single agent.**\n"
        "\n"
        "All three yes → orchestrate. Any no → simpler.\n"
    ),
    md(
        "## 13. Self-check\n"
        "\n"
        "1. What's the default reducer if you don't annotate a field? What's the consequence in parallel branches?\n"
        "2. When do you use static edges vs the `Send` API for fan-out?\n"
        "3. A researcher crashes mid-superstep. What does LangGraph preserve, and what gets re-run on retry?\n"
        "4. We did NOT use a checkpointer in this notebook. What capability do we *not* have? (Hint: notebook 08.)\n"
        "5. Compare line counts: hand-rolled 07 vs LangGraph 07b. What's the *real* difference?\n"
        "\n"
        "## What's next\n"
        "\n"
        "Notebook **08 capstone extension** — add `SqliteSaver` + `interrupt()` + `get_state_history`:\n"
        "- The brief now pauses for human approval via `interrupt()` (durable HITL, replaces `ApprovalStore`).\n"
        "- Editor can close their browser, come back tomorrow, resume.\n"
        "- We demonstrate time-travel by forking from a prior checkpoint with modified sub-questions.\n"
        "\n"
        "Notebook **09 production pipeline** — wrap the LangGraph app in Redis Streams + FastAPI SSE:\n"
        "- FastAPI POST `/runs` enqueues a task.\n"
        "- Worker consumes, acquires SETNX lock, runs the graph, streams progress, stores result.\n"
        "- This is S9 Part 5 — the lecture maps line-by-line to the code.\n"
    ),
]

write("notebooks/07b_langgraph_rewrite.ipynb", cells)
print("wrote notebooks/07b_langgraph_rewrite.ipynb")
