"""Generator for notebooks/08b_langgraph_hitl.ipynb."""

from build_notebook import code, md, write

cells = [
    md(
        "# 08b — Capstone Upgrade: `SqliteSaver` + `interrupt()` + Time Travel\n"
        "\n"
        "Notebook 08 built a tier-2 HITL gate **by hand** — `ApprovalStore` with a `pending/` "
        "directory of JSON files and a 500ms polling loop. It works. It's also exactly the kind of "
        "wheel LangGraph reinvented properly.\n"
        "\n"
        "This notebook replaces all of it with **three LangGraph primitives**:\n"
        "\n"
        "1. **Checkpointer** (`SqliteSaver`) — every superstep's state survives process restart\n"
        "2. **`interrupt()`** — durable HITL inside a node, no polling, no approval table\n"
        "3. **Time travel** — `app.get_state_history(config)` returns every checkpoint; fork + replay any of them\n"
        "\n"
        "**By the end of this notebook you will:**\n"
        "1. Run a research pipeline that pauses at `interrupt()` and inspect what's preserved\n"
        "2. **Kill the Python app object mid-run**, recreate it from scratch, and resume — proving the state is durable\n"
        "3. Resume with `Command(resume=...)` and watch the graph continue from exactly where it paused\n"
        "4. Use `get_state_history` to reproduce the agent's behavior and fork from an earlier point with modified state\n"
        "\n"
        "Lecture references: **S9 §3.1** (Checkpointer), **S9 §3.2** (`interrupt()`), **S9 §3.3** (Time travel).\n"
    ),
    md(
        "## 1. Why the hand-rolled `ApprovalStore` isn't enough\n"
        "\n"
        "Notebook 08's flow:\n"
        "\n"
        "```\n"
        "draft ready → ApprovalStore.create() → file in pending/  \n"
        "  Python kernel sits in `await wait_for_decision()` polling every 500ms  \n"
        "  ipywidgets button click → ApprovalStore.decide() → file moves to decided/  \n"
        "  poll loop sees state change → returns → save brief\n"
        "```\n"
        "\n"
        "Four limitations:\n"
        "\n"
        "| What hurts | Why |\n"
        "|---|---|\n"
        "| The Python process must stay alive | Polling loop holds the await. Worker recycle = brief abandoned. |\n"
        "| Only the approval state is saved | All the in-flight research state lives in `agent.run()` locals. Crash mid-run = restart from scratch. |\n"
        "| No way to inspect what the agent did at each step | The trace is in memory. After the cell finishes, it's gone. |\n"
        "| 500ms polling burns CPU + adds latency | Acceptable in a notebook. Wasteful at fleet scale. |\n"
        "\n"
        "LangGraph fixes all four with one wiring change. We don't write more code — we write **different** code.\n"
    ),
    md(
        "## 2. Setup"
    ),
    code(
        "import asyncio\n"
        "import os\n"
        "import tempfile\n"
        "from pathlib import Path\n"
        "\n"
        "from dotenv import load_dotenv\n"
        "load_dotenv()\n"
        "assert os.getenv(\"OPENAI_API_KEY\"), \"Set OPENAI_API_KEY in .env\"\n"
        "\n"
        "from langgraph.checkpoint.sqlite import SqliteSaver\n"
        "from langgraph.types import Command\n"
        "\n"
        "# We use a tempfile-backed sqlite db so this notebook is hermetic.\n"
        "# In production: use AsyncPostgresSaver pointing at a real Postgres.\n"
        "DB_PATH = str(Path(tempfile.gettempdir()) / \"deepbrief_capstone.db\")\n"
        "print(f\"checkpointer db: {DB_PATH}\")"
    ),
    md(
        "## 3. The new graph: `langgraph_capstone.py`\n"
        "\n"
        "We've added one node — `review` — to the graph from notebook 07b. The whole capstone source "
        "lives at `src/deepbrief/agents/langgraph_capstone.py`."
    ),
    code(
        "import inspect\n"
        "from deepbrief.agents.langgraph_capstone import (\n"
        "    CapstoneState, review_node, needs_revision,\n"
        "    build_capstone_graph, build_capstone_app, empty_state,\n"
        ")\n"
        "\n"
        "print(\"=== CapstoneState ===\")\n"
        "print(inspect.getsource(CapstoneState))\n"
        "\n"
        "print(\"=== review_node (where interrupt() lives) ===\")\n"
        "print(inspect.getsource(review_node))"
    ),
    md(
        "**The whole new pattern is in `review_node`.** Five things to call out (S9 §3.2):\n"
        "\n"
        "**(a) `interrupt(payload)` is a function call inside the node.** Not a config flag, not a "
        "decorator. The node decides when to pause — based on state. You can interrupt unconditionally "
        "for tier-2 actions or conditionally on risk score.\n"
        "\n"
        "**(b) The payload is by convention.** Any JSON-serializable dict. Surface it to a UI; the UI's "
        "schema is yours to define.\n"
        "\n"
        "**(c) `interrupt(...)` literally returns the resume value.** When the human resumes via "
        "`Command(resume=\"approve\")`, the *same line* of code that initially called `interrupt(...)` "
        "now evaluates to `\"approve\"` and execution continues. The graph rehydrates and walks forward.\n"
        "\n"
        "**(d) `MAX_REVISIONS = 2` is our termination guard.** Without it the reviewer + LLM can bounce "
        "forever — `synthesize → review → synthesize → review → ...`. Map this to S8's loop-cap discipline.\n"
        "\n"
        "**(e) `needs_revision` is the conditional edge.** It reads `approved` and `reviewer_notes` and "
        "decides END or back-to-synthesize.\n"
    ),
    md(
        "## 4. Build the app — checkpointer is required\n"
        "\n"
        "Two-step compile:"
    ),
    code(
        "# SqliteSaver from_conn_string is a context manager. For the notebook we keep it open\n"
        "# for the duration of the cells using contextlib.ExitStack so multiple cells can share it.\n"
        "from contextlib import ExitStack\n"
        "\n"
        "stack = ExitStack()\n"
        "checkpointer = stack.enter_context(SqliteSaver.from_conn_string(DB_PATH))\n"
        "app = build_capstone_app(checkpointer)\n"
        "print(\"app compiled with SqliteSaver — interrupt() will work\")"
    ),
    md(
        "**Why is the checkpointer required?**\n"
        "\n"
        "`interrupt()` writes state to durable storage and returns control to the caller. If there's no "
        "checkpointer, there's nowhere to write — the call would lose all state. LangGraph guards "
        "against this: `build_capstone_app(None)` raises `ValueError`.\n"
        "\n"
        "**`thread_id` is the unit of state isolation.** Each thread has its own checkpoint history. "
        "Multi-tenant systems share one graph across millions of conversations by partitioning on "
        "`thread_id` — same schema, isolated data."
    ),
    md(
        "## 5. First call — runs until `interrupt()`\n"
        "\n"
        "Same topic as notebook 07b for direct comparison. The call returns when the graph hits `review`."
    ),
    code(
        "TOPIC = \"State of agent-protocol adoption: MCP vs A2A in 2026\"\n"
        "THREAD_ID = \"capstone-demo-1\"\n"
        "config = {\"configurable\": {\"thread_id\": THREAD_ID}}\n"
        "\n"
        "# Run until the graph pauses\n"
        "result = await app.ainvoke(empty_state(TOPIC), config=config)\n"
        "\n"
        "print(\"=== top-level result keys ===\")\n"
        "for k, v in result.items():\n"
        "    if k == \"__interrupt__\":\n"
        "        print(f\"  {k}: {v}\")\n"
        "    elif isinstance(v, (str, int, float, bool)) or v is None:\n"
        "        print(f\"  {k}: {v}\")\n"
        "    else:\n"
        "        print(f\"  {k}: <{type(v).__name__} of len {len(v)}>\")"
    ),
    md(
        "Notice the **`__interrupt__`** key — that's how LangGraph tells the caller \"the graph paused.\" "
        "The payload contains exactly what we passed to `interrupt(...)`.\n"
        "\n"
        "Also notice that **`draft` is populated** even though `approved` is still `False`. The graph "
        "got all the way through `synthesize`, paused inside `review`, and surfaced the partial state "
        "back to us. **All the research work is done and persisted** — the only thing waiting is the human."
    ),
    md(
        "## 6. The dramatic move: kill the app, recreate it, prove durability\n"
        "\n"
        "Here's the test that the hand-rolled `ApprovalStore` could pass too, but `SqliteSaver` passes "
        "**without us writing any save/load code**. We're going to:\n"
        "\n"
        "1. Delete the compiled `app` object\n"
        "2. Wait (simulate a process restart — but in-notebook it's instant)\n"
        "3. Rebuild a brand new app from scratch\n"
        "4. Connect to the **same** sqlite db + thread_id\n"
        "5. Inspect the state — it should be sitting at the `review` interrupt\n"
    ),
    code(
        "# Drop the old app reference\n"
        "del app, checkpointer\n"
        "stack.close()\n"
        "print(\"Old app + checkpointer destroyed.\\n\")\n"
        "\n"
        "# Recreate from scratch — same DB, same thread_id\n"
        "stack = ExitStack()\n"
        "new_checkpointer = stack.enter_context(SqliteSaver.from_conn_string(DB_PATH))\n"
        "app = build_capstone_app(new_checkpointer)\n"
        "print(\"New app compiled. Reading state from sqlite...\\n\")\n"
        "\n"
        "snapshot = app.get_state(config)\n"
        "print(f\"  current values keys:   {list(snapshot.values.keys())}\")\n"
        "print(f\"  next node to execute:  {snapshot.next}\")\n"
        "print(f\"  __interrupt__ pending? {bool(snapshot.tasks)}\")\n"
        "print(f\"  topic:                 {snapshot.values['topic']}\")\n"
        "print(f\"  findings count:        {len(snapshot.values['findings'])}\")\n"
        "print(f\"  draft length:          {len(snapshot.values['draft'] or '')}\")"
    ),
    md(
        "**Read the output carefully.** A brand new Python object — different memory, no shared state "
        "with the original `app` — has just loaded the **complete in-flight state** from a sqlite file, "
        "including:\n"
        "\n"
        "- The topic\n"
        "- All N findings (the parallel research output)\n"
        "- The synthesized draft\n"
        "- The pending interrupt (the `next: ('review',)` confirms the graph is paused at review)\n"
        "\n"
        "**This is the production property the hand-rolled `ApprovalStore` doesn't give you.** "
        "ApprovalStore saved the *approval request*. SqliteSaver saves the *entire agent state*.\n"
    ),
    md(
        "## 7. Resume with `Command(resume=...)`\n"
        "\n"
        "Now we feed a decision back into the paused `interrupt()` call. The graph rehydrates from "
        "the checkpoint, the `interrupt(...)` call returns our `value`, and `review_node` continues "
        "with that decision."
    ),
    code(
        "# Approve the brief — the simplest case\n"
        "final = await app.ainvoke(Command(resume=\"approve\"), config=config)\n"
        "\n"
        "print(\"=== final state after resume ===\")\n"
        "print(f\"  approved:        {final['approved']}\")\n"
        "print(f\"  reviewer_notes:  {final.get('reviewer_notes')}\")\n"
        "print(f\"  revision_count:  {final.get('revision_count', 0)}\")\n"
        "print(f\"  __interrupt__:   {final.get('__interrupt__', None)}\")\n"
        "\n"
        "print(\"\\n=== final brief ===\")\n"
        "print(final[\"draft\"])"
    ),
    md(
        "## 8. The revision loop — resume with `revise` instead of `approve`\n"
        "\n"
        "What if the reviewer doesn't like the draft? `Command(resume={\"action\": \"revise\", \"notes\": \"...\"})` "
        "loops back to `synthesize`, which re-runs with the same `findings` (we don't re-research — "
        "we only re-synthesize). After `MAX_REVISIONS = 2` rounds, `review_node` auto-approves to "
        "prevent infinite loops.\n"
        "\n"
        "Let's prove it on a fresh thread."
    ),
    code(
        "# Fresh thread for the revision-loop demo\n"
        "REVISE_THREAD = \"capstone-revise-demo\"\n"
        "revise_config = {\"configurable\": {\"thread_id\": REVISE_THREAD}}\n"
        "\n"
        "result = await app.ainvoke(empty_state(\"What is FastMCP?\"), config=revise_config)\n"
        "print(\"first pause — draft v1 ready, asking for review\")\n"
        "\n"
        "# Reviewer asks for a revision\n"
        "result = await app.ainvoke(\n"
        "    Command(resume={\"action\": \"revise\", \"notes\": \"too technical — add a 1-sentence summary at the top\"}),\n"
        "    config=revise_config,\n"
        ")\n"
        "print(\"second pause — draft v2 ready\")\n"
        "print(f\"  revision_count now: {result.get('revision_count', 0)}\")\n"
        "\n"
        "# Approve the second draft\n"
        "result = await app.ainvoke(Command(resume=\"approve\"), config=revise_config)\n"
        "print(\"done\")\n"
        "print(f\"  approved={result['approved']}  revision_count={result.get('revision_count', 0)}\")\n"
        "print(f\"\\nfinal draft (length={len(result['draft'])}):\")\n"
        "print(result['draft'][:400] + (\"...\" if len(result['draft']) > 400 else \"\"))"
    ),
    md(
        "Two things just happened that the hand-rolled `ApprovalStore` couldn't do cleanly:\n"
        "\n"
        "**(a) State preservation across the revision round.** The `findings` list survived the "
        "synthesize → review → synthesize cycle untouched — same researchers' output, only the LLM "
        "re-merges with the reviewer's notes. With `ApprovalStore` you'd have to re-run the whole "
        "pipeline or write custom save-and-restore for the intermediate state.\n"
        "\n"
        "**(b) The reviewer's structured payload was passed through.** `Command(resume={\"action\": "
        "\"revise\", \"notes\": \"...\"})` — the dict is returned by `interrupt(...)` exactly as-is. "
        "The notes can flow into the next synthesize step's prompt if you want — full editorial control.\n"
    ),
    md(
        "## 9. Time travel — inspect every checkpoint\n"
        "\n"
        "**The senior-grade superpower** (S9 §3.3): `app.get_state_history(config)` returns every "
        "checkpoint ever taken for this thread. You can inspect them, fork from any of them, replay.\n"
        "\n"
        "This is the answer to the interview question *\"a user reports the agent gave a different "
        "answer this time — how do you reproduce?\"*"
    ),
    code(
        "# List every checkpoint for the approval thread (the first demo, not the revise demo)\n"
        "snapshots = list(app.get_state_history(config))\n"
        "print(f\"Total snapshots: {len(snapshots)}\\n\")\n"
        "\n"
        "for i, snap in enumerate(snapshots):\n"
        "    n_findings = len(snap.values.get(\"findings\", []))\n"
        "    has_draft = bool(snap.values.get(\"draft\"))\n"
        "    approved = snap.values.get(\"approved\", False)\n"
        "    next_node = snap.next or (\"END\",)\n"
        "    print(f\"  [{i:2d}] next={str(next_node):20s}  findings={n_findings}  draft={'yes' if has_draft else 'no '}  approved={approved}\")"
    ),
    md(
        "Each row is a snapshot taken after one superstep. You can see the state evolving — "
        "no findings → 1 finding → 2 → 3 → draft appears → approved → done.\n"
        "\n"
        "**This trace is free.** You did not write a single `trace.append()` call. Compare with S8's "
        "hand-rolled `trace = []` list — same information, but now durable and queryable."
    ),
    md(
        "## 10. Time travel — fork from a prior checkpoint with modified state\n"
        "\n"
        "Pick a snapshot from before `synthesize` ran. Modify `findings` (pretend a researcher returned "
        "different data). Replay from that point. The graph re-runs only the affected downstream nodes."
    ),
    code(
        "# Find the snapshot right after research_node ran (so we can modify findings before synthesize)\n"
        "pre_synth = next(\n"
        "    s for s in snapshots\n"
        "    if s.next == (\"synthesize\",)\n"
        ")\n"
        "print(\"forking from this snapshot:\")\n"
        "print(f\"  next = {pre_synth.next}\")\n"
        "print(f\"  findings count = {len(pre_synth.values['findings'])}\")\n"
        "print(f\"  checkpoint_id  = {pre_synth.config['configurable']['checkpoint_id']}\")\n"
        "\n"
        "# Build a fork config pointing at that exact checkpoint\n"
        "fork_config = {\n"
        "    \"configurable\": {\n"
        "        \"thread_id\": THREAD_ID,\n"
        "        \"checkpoint_id\": pre_synth.config[\"configurable\"][\"checkpoint_id\"],\n"
        "    }\n"
        "}\n"
        "\n"
        "# Mutate state at the fork point — replace findings with a doctored version\n"
        "doctored_findings = list(pre_synth.values[\"findings\"])\n"
        "if doctored_findings:\n"
        "    doctored_findings[0] = {\n"
        "        **doctored_findings[0],\n"
        "        \"summary\": \"[DOCTORED FOR TIME-TRAVEL DEMO] First finding now says MCP was created by the Linux Foundation in 2024 — wrong on purpose.\",\n"
        "    }\n"
        "\n"
        "# update_state writes a new checkpoint at the fork point\n"
        "app.update_state(fork_config, {\"findings\": doctored_findings, \"draft\": None})\n"
        "\n"
        "# Re-invoke from the fork — synthesize re-runs with the doctored findings\n"
        "forked = await app.ainvoke(None, config=fork_config)\n"
        "print(\"\\n=== forked draft (should reflect the doctored finding) ===\")\n"
        "print(forked.get(\"draft\", \"<paused>\")[:500])"
    ),
    md(
        "If everything worked, the forked draft's text differs from the original — because synthesize "
        "ran against the doctored findings. **You just A/B-tested the synthesize step with surgical "
        "input control**, without re-running the expensive research nodes.\n"
        "\n"
        "**This is the time-travel pattern** — fork → update_state → ainvoke. Three lines, the entire "
        "reproducibility story.\n"
        "\n"
        "Real worked example: see [DEV.to time-travel debugging a loan-rejection agent](https://dev.to). "
        "The pattern generalizes — banking, compliance, any agent where you need to defend a decision.\n"
    ),
    md(
        "## 11. Mapping back to S8's HITL 4-tier taxonomy\n"
        "\n"
        "S8 §5.5 said: *\"This taxonomy is not encoded per-agent. It is a fleet-wide policy.\"* "
        "LangGraph gives us the primitives to implement each tier consistently:\n"
        "\n"
        "| Tier | Risk | Lecture mode | LangGraph implementation |\n"
        "|---|---|---|---|\n"
        "| **0** | Read-only, idempotent | Auto + log only | No `interrupt`; just trace via `astream_events` |\n"
        "| **1** | Non-critical writes | Logged async | No `interrupt`; emit event to a reviewer queue (Redis pub/sub) |\n"
        "| **2** | Irreversible writes / customer-facing | **Sync HITL** | `interrupt()` — exactly what we just built |\n"
        "| **3** | Regulated / high-stakes | Hard block | Don't propose; refuse in the planner |\n"
        "\n"
        "The neat property: **all four tiers share the same agent code base** — only the node-level "
        "policy decides which tier applies. New action type? Tag it with a tier; the runtime takes care "
        "of the rest. Fleet-wide consistency for free.\n"
    ),
    md(
        "## 12. Cleanup"
    ),
    code(
        "stack.close()\n"
        "if os.path.exists(DB_PATH):\n"
        "    os.remove(DB_PATH)\n"
        "    print(f\"removed {DB_PATH}\")"
    ),
    md(
        "## 13. Self-check\n"
        "\n"
        "1. Why does `interrupt()` require a checkpointer? What would go wrong without one?\n"
        "2. We killed the `app` object mid-run and recreated it. What did the new app object inherit from the old? Where was the state physically stored?\n"
        "3. `Command(resume=...)` can be a string, a dict, anything JSON-serializable. What's the architectural reason to use a dict over a string in production?\n"
        "4. We capped revisions with `MAX_REVISIONS = 2`. What's the runaway scenario this guards against?\n"
        "5. Walk through what `app.update_state(fork_config, {\"findings\": doctored})` actually does. Where does the doctored data physically end up?\n"
        "\n"
        "## What's next\n"
        "\n"
        "Notebook **09 — production pipeline**. We've got an agent that's durable and interruptable. "
        "Now we need to run it as a **worker consuming from a queue**, with idempotency, progress emission, "
        "and durable result storage. That's S9 Part 5 — the operational scaffolding around the agent. "
        "It maps line-by-line to the lecture.\n"
    ),
]

write("notebooks/08b_langgraph_hitl.ipynb", cells)
print("wrote notebooks/08b_langgraph_hitl.ipynb")
