"""Generator for notebooks/08_hitl_capstone.ipynb."""

from build_notebook import code, md, write

cells = [
    md(
        "# 08 — HITL Capstone: The Full DeepBrief\n"
        "\n"
        "All the pieces are built. We have:\n"
        "\n"
        "| From notebook | We built |\n"
        "|---|---|\n"
        "| 01-03 | Bounded ReAct agent loop with cost & loop guards |\n"
        "| 04-05 | Two MCP servers (notes, cache) on stdio + Streamable HTTP |\n"
        "| 06    | Adapter that lets the agent treat MCP tools and native tools the same |\n"
        "| 07    | Coordinator + parallel researchers via A2A |\n"
        "\n"
        "**One thing missing.** Right now the system writes a brief and saves it. That's a Tier-2 action — "
        "irreversible, customer-facing, our name is on it. Production agents do NOT auto-publish. "
        "They route to a **human-in-the-loop editor** for sync approval.\n"
        "\n"
        "**By the end of this notebook you will:**\n"
        "1. Build a durable approval queue (survives process restarts)\n"
        "2. Wire the editor as a sync gate between synthesis and save\n"
        "3. Approve via inline `ipywidgets` buttons — that's the production UX shape\n"
        "4. Run the **complete DeepBrief** end-to-end and inspect the saved brief\n"
        "\n"
        "Lecture reference: **S8 §5.5** (HITL approval gates).\n"
    ),
    md(
        "## 1. The 4-tier HITL taxonomy\n"
        "\n"
        "| Tier | Risk class | Examples | Mode |\n"
        "|---|---|---|---|\n"
        "| **0** | Read-only, idempotent | DB read, web search, weather | **Auto** — log only |\n"
        "| **1** | Non-critical writes, low blast radius | Send notification, file ticket | Logged async (audit sample) |\n"
        "| **2** | Irreversible writes, $ involved | **Save customer brief**, send email, modify staging | **Sync HITL** ← we are here |\n"
        "| **3** | Regulated / high-stakes | Charge > $X, prod data write, customer-facing comms | Block; multi-approver if needed |\n"
        "\n"
        "**Senior-level insight:** this taxonomy is not encoded per-agent. It's a **fleet-wide policy**. "
        "Every agent in the system is subject to the same tier rules. When a new agent adds a new "
        "action type, the policy classification governs it by default — the developer doesn't need to "
        "think about it. (See [Waxell, *Human-in-the-Loop vs Human-on-the-Loop*](https://www.waxell.ai/blog/human-in-the-loop-vs-human-on-the-loop-ai-agents).)\n"
    ),
    md(
        "## 2. Read the editor\n"
        "\n"
        "`ApprovalStore` lives at `src/deepbrief/agents/editor.py`. Two design choices:\n"
        "\n"
        "1. **File-backed** — pending approvals are JSON files in `./data/approvals/pending/`. Decided "
        "ones move to `./data/approvals/decided/`. Survives process restart.\n"
        "2. **`wait_for_decision` polls** — async loop that checks every 500ms. In production you'd use "
        "a Redis pub/sub or webhook. The polling pattern works everywhere and is trivial to debug."
    ),
    code(
        "import inspect\n"
        "from deepbrief.agents.editor import ApprovalStore, ApprovalRequest\n"
        "\n"
        "src = inspect.getsource(ApprovalStore)\n"
        "print(src[:2000])\n"
        "print(\"... [decide() and wait_for_decision()] ...\")"
    ),
    md(
        "## 3. Start the researchers\n"
        "\n"
        "Same as notebook 07 — two researcher subprocesses on 9001/9002. If yours from before are still "
        "running, the `pkill` line cleans up first."
    ),
    code(
        "import os, subprocess, sys, time\n"
        "\n"
        "subprocess.run([\"pkill\", \"-f\", \"deepbrief.agents.researcher\"], capture_output=True)\n"
        "time.sleep(1)\n"
        "\n"
        "researchers = [\n"
        "    subprocess.Popen(\n"
        "        [sys.executable, \"-m\", \"deepbrief.agents.researcher\", \"--port\", str(p)],\n"
        "        stdout=subprocess.PIPE, stderr=subprocess.PIPE,\n"
        "        env=os.environ.copy(),\n"
        "    )\n"
        "    for p in [9001, 9002]\n"
        "]\n"
        "time.sleep(3)\n"
        "for proc, port in zip(researchers, [9001, 9002]):\n"
        "    print(f\":{port} alive={proc.poll() is None}\")"
    ),
    md(
        "## 4. Run the coordinator and produce a draft"
    ),
    code(
        "from dotenv import load_dotenv\n"
        "load_dotenv()\n"
        "\n"
        "from deepbrief.agents.coordinator import Coordinator\n"
        "\n"
        "TOPIC = \"State of agent-protocol adoption: MCP vs A2A in 2026\"\n"
        "\n"
        "coordinator = Coordinator(researcher_urls=[\n"
        "    \"http://localhost:9001\",\n"
        "    \"http://localhost:9002\",\n"
        "])\n"
        "draft = await coordinator.run(TOPIC)\n"
        "print(draft.markdown)"
    ),
    md(
        "## 5. Queue the brief for human approval"
    ),
    code(
        "store = ApprovalStore(base_dir=\"./data/approvals\")\n"
        "req = store.create(topic=TOPIC, draft_markdown=draft.markdown)\n"
        "print(f\"📬 Created request {req.request_id}\")\n"
        "print(f\"   pending file: ./data/approvals/pending/{req.request_id}.json\")\n"
        "print(f\"   state: {req.state}\")"
    ),
    md(
        "## 6. Approve via ipywidgets (the production UX shape)\n"
        "\n"
        "In a real product the editor surface is a web UI — Slack DM, internal admin panel, dashboard "
        "card. In a notebook we use `ipywidgets` to mimic the same shape: three buttons, one decision."
    ),
    code(
        "import ipywidgets as widgets\n"
        "from IPython.display import display, Markdown\n"
        "\n"
        "approve_btn = widgets.Button(description=\"✅ Approve\", button_style=\"success\")\n"
        "reject_btn  = widgets.Button(description=\"❌ Reject\", button_style=\"danger\")\n"
        "edit_btn    = widgets.Button(description=\"✏️ Edit & approve\", button_style=\"warning\")\n"
        "edit_box    = widgets.Textarea(value=draft.markdown, layout=widgets.Layout(width=\"100%\", height=\"200px\"))\n"
        "status      = widgets.HTML(value=f\"<i>request {req.request_id} — pending</i>\")\n"
        "\n"
        "def _approve(_):\n"
        "    store.decide(req.request_id, \"approved\", decided_by=\"notebook\")\n"
        "    status.value = f\"<b>✅ approved</b> ({req.request_id})\"\n"
        "\n"
        "def _reject(_):\n"
        "    store.decide(req.request_id, \"rejected\", decided_by=\"notebook\")\n"
        "    status.value = f\"<b>❌ rejected</b> ({req.request_id})\"\n"
        "\n"
        "def _edit(_):\n"
        "    store.decide(\n"
        "        req.request_id, \"edited\",\n"
        "        decided_by=\"notebook\", final_markdown=edit_box.value,\n"
        "    )\n"
        "    status.value = f\"<b>✏️ edited & approved</b> ({req.request_id})\"\n"
        "\n"
        "approve_btn.on_click(_approve)\n"
        "reject_btn.on_click(_reject)\n"
        "edit_btn.on_click(_edit)\n"
        "\n"
        "display(widgets.VBox([\n"
        "    widgets.HTML(\"<h3>Review the draft, then click one button:</h3>\"),\n"
        "    widgets.HBox([approve_btn, reject_btn, edit_btn]),\n"
        "    widgets.HTML(\"<b>Edit field</b> (used only if you click 'Edit & approve'):\"),\n"
        "    edit_box,\n"
        "    status,\n"
        "]))"
    ),
    md(
        "**Click one of the buttons above** before running the next cell. The next cell calls "
        "`wait_for_decision` which blocks (polling) until you decide. If the kernel were a worker process "
        "it could be killed and restarted between create + decide, and the decision would still be "
        "captured because everything is on disk."
    ),
    code(
        "decision = await store.wait_for_decision(req.request_id, timeout_s=300)\n"
        "print(f\"state:       {decision.state}\")\n"
        "print(f\"decided_by:  {decision.decided_by}\")\n"
        "print(f\"decided_at:  {decision.decided_at}\")"
    ),
    md(
        "## 7. Save the brief (or skip if rejected)"
    ),
    code(
        "from datetime import datetime, timezone\n"
        "from pathlib import Path\n"
        "import re\n"
        "\n"
        "if decision.state == \"rejected\":\n"
        "    print(\"❌ Rejected — nothing saved.\")\n"
        "else:\n"
        "    briefs_dir = Path(\"./data/briefs\")\n"
        "    briefs_dir.mkdir(parents=True, exist_ok=True)\n"
        "    slug = re.sub(r\"[^a-z0-9]+\", \"-\", TOPIC.lower()).strip(\"-\")[:50]\n"
        "    ts = datetime.now(timezone.utc).strftime(\"%Y%m%d-%H%M%S\")\n"
        "    out_path = briefs_dir / f\"{ts}-{slug}.md\"\n"
        "    out_path.write_text(decision.final_markdown)\n"
        "    print(f\"📄 Saved: {out_path}\")\n"
        "    display(Markdown(decision.final_markdown))"
    ),
    md(
        "## 8. The whole pipeline as a script\n"
        "\n"
        "Everything we just did is also wired up in `src/deepbrief/run.py`. From a terminal:\n"
        "\n"
        "```bash\n"
        "# Start researchers in two other terminals first:\n"
        "python -m deepbrief.agents.researcher --port 9001\n"
        "python -m deepbrief.agents.researcher --port 9002\n"
        "\n"
        "# Then run the pipeline. CLI prompts for approval.\n"
        "python -m deepbrief.run \"State of WebGPU adoption in 2026\"\n"
        "\n"
        "# Or in CI, skip the gate:\n"
        "python -m deepbrief.run --auto-approve \"a topic\"\n"
        "\n"
        "# Or queue for async review:\n"
        "python -m deepbrief.run --queue-only \"a topic\"\n"
        "```\n"
    ),
    md(
        "## 9. What you have now (and what's missing)\n"
        "\n"
        "**Have:**\n"
        "- ReAct loop with parallel tool calls + graceful termination (S8 §3, §4)\n"
        "- Strict mode + structured tool layer (S8 §6)\n"
        "- Cost / loop / step caps with budget enforcement (S8 §4)\n"
        "- Two MCP servers, two transports, generic adapter into the tool registry (S7 §3-§5)\n"
        "- Coordinator + parallel researchers via A2A protocol (S7 §7)\n"
        "- Tier-2 sync HITL gate with durable approval state (S8 §5.5)\n"
        "\n"
        "**Missing — extension exercises for you:**\n"
        "1. **Streaming A2A** (`tasks/sendSubscribe`) — researchers emit progress events the coordinator "
        "can show in a UI. Currently we just block.\n"
        "2. **Real observability** — emit OpenTelemetry GenAI spans (S8 §7.2) to Langfuse instead of "
        "in-memory `trace`. ~30 minutes with the `langfuse` Python SDK.\n"
        "3. **MCP gateway** — put Bifrost or supergateway in front of the MCP servers; centralize auth, "
        "rate limit, audit. (S7 §8.)\n"
        "4. **Loop semantic guard** — embed tool args, cosine-similarity threshold against history. "
        "Catches `\"weather Paris\"` ↔ `\"current Paris weather\"` drift that the literal hash misses.\n"
        "5. **Code Mode** — instead of sending all 8+ tool schemas every call, let the coordinator emit "
        "Python that *uses* the tools as imports, sandbox-execute it. Bifrost's reported impact: ~50% "
        "fewer prompt tokens. (S7 §8.3.)\n"
    ),
    md(
        "## 10. Cleanup"
    ),
    code(
        "for proc in researchers:\n"
        "    proc.terminate()\n"
        "    try:\n"
        "        proc.wait(timeout=5)\n"
        "    except subprocess.TimeoutExpired:\n"
        "        proc.kill()\n"
        "print(\"researchers stopped\")"
    ),
    md(
        "## 11. Final self-check\n"
        "\n"
        "1. Why is the editor a Tier 2 action and not Tier 1 or Tier 3? Defend the classification.\n"
        "2. The approval store uses files instead of an in-memory dict. What problem would the in-memory "
        "version have under a real worker recycling event?\n"
        "3. We poll for decisions every 500ms. What's the production-grade alternative? When would polling actually win?\n"
        "4. Where in the pipeline is the *only* place you'd want to bypass HITL during an outage?\n"
        "5. You're on call and the editor surface is down. The coordinator has 200 pending briefs. What's your fallback?\n"
        "\n"
        "## You're done.\n"
        "\n"
        "You've now built every piece of an industrial agent system in ~700 lines of Python. The patterns "
        "scale: VoyageAI's production worker uses the same shape (ReAct + MCP + Kafka + MongoDB + HITL) "
        "— just bigger.\n"
        "\n"
        "**Forward links:**\n"
        "- S9 — Tool-RAG: when you have 30+ MCP tools, semantic retrieval to pick which 5 schemas to send each turn\n"
        "- S10 — Stateful agents: cross-session memory, agent checkpointing\n"
        "- S15 — Multi-model routing: send Tier 0 calls to gpt-4o-mini, Tier 3 to o1\n"
        "\n"
        "Good luck on interviews. 🚀"
    ),
]

write("notebooks/08_hitl_capstone.ipynb", cells)
print("wrote notebooks/08_hitl_capstone.ipynb")
