"""Generator for notebooks/09_production_pipeline.ipynb."""

from build_notebook import code, md, write

cells = [
    md(
        "# 09 — Production Pipeline: Redis Streams + Worker + SSE\n"
        "\n"
        "Through notebook 08b we have an agent that's **stateful and interruptible**. "
        "Now we make it run **as a worker behind a queue**.\n"
        "\n"
        "**Why this matters.** Notebook 07b's `app.ainvoke()` is fine for a notebook. But production "
        "agents need:\n"
        "- The user can close their browser; the agent keeps running\n"
        "- N workers can consume the same queue (horizontal scale)\n"
        "- A worker crash redelivers — and **must not re-bill** a task that already completed\n"
        "- The UI wants a live progress bar (SSE), not a 60-second blank screen\n"
        "\n"
        "**By the end of this notebook you will:**\n"
        "1. Enqueue tasks to a Redis Stream and watch a worker consume them\n"
        "2. See the **SETNX idempotency lock** prevent double-execution under simulated redelivery\n"
        "3. Stream progress events via Redis Pub/Sub as the agent runs\n"
        "4. Verify the **six-step ordering** from S9 §5.4 — consume → check → lock → run → store → ack\n"
        "5. (Optional) Wire in the real LangGraph brief from notebook 07b for end-to-end\n"
        "\n"
        "Lecture reference: **S9 Part 5** (entire chapter maps to this notebook).\n"
    ),
    md(
        "## 1. Start Redis\n"
        "\n"
        "This notebook needs a local Redis. Three options:\n"
        "\n"
        "```bash\n"
        "# Option A — Docker (recommended, isolated)\n"
        "docker run -d --name deepbrief-redis -p 6379:6379 redis:7-alpine\n"
        "\n"
        "# Option B — Homebrew on macOS\n"
        "brew install redis && brew services start redis\n"
        "\n"
        "# Option C — apt on Debian / Ubuntu\n"
        "sudo apt install redis-server && sudo systemctl start redis\n"
        "```\n"
        "\n"
        "Verify with `redis-cli ping` → `PONG`."
    ),
    code(
        "import os\n"
        "from dotenv import load_dotenv\n"
        "load_dotenv()\n"
        "\n"
        "from redis.asyncio import Redis\n"
        "\n"
        "REDIS_URL = os.getenv(\"REDIS_URL\", \"redis://localhost:6379/0\")\n"
        "redis = await Redis.from_url(REDIS_URL)\n"
        "\n"
        "# Confirm we can talk to Redis\n"
        "pong = await redis.ping()\n"
        "print(f\"Redis @ {REDIS_URL}: {'OK' if pong else 'NO'}\")\n"
        "assert pong, \"Redis not reachable — start it (see the markdown cell above)\""
    ),
    md(
        "Clean any leftover state from previous runs of this notebook so the demos are deterministic:"
    ),
    code(
        "from deepbrief.pipeline.streams import STREAM\n"
        "\n"
        "# Wipe out the stream + any old consumer groups so the demo starts clean\n"
        "await redis.delete(STREAM)\n"
        "# Lock keys + run records\n"
        "for key in await redis.keys(\"agent:lock:*\"):\n"
        "    await redis.delete(key)\n"
        "\n"
        "import os, pathlib\n"
        "db = pathlib.Path(\"./data/runs.db\")\n"
        "if db.exists():\n"
        "    db.unlink()\n"
        "print(\"clean state — ready to demo\")"
    ),
    md(
        "## 2. The pipeline shape\n"
        "\n"
        "Five small files in `src/deepbrief/pipeline/`. Each maps to one box in the lecture diagram:\n"
        "\n"
        "```\n"
        "┌──────────────────┐  enqueue()      ┌─────────────────┐  consume_loop()  ┌────────────────┐\n"
        "│ Producer         │ ──────────────▶ │ Queue           │ ───────────────▶ │ Worker         │\n"
        "│ FastAPI POST /runs│                │ Redis Stream    │                  │ 6-step loop    │\n"
        "└──────────────────┘                 │ `agent:runs`    │                  │                │\n"
        "                                     └─────────────────┘                  └────────────────┘\n"
        "                                                                                 │\n"
        "                                                            store.insert_one()   ▼\n"
        "                                                            ┌─────────────┐\n"
        "                                                            │ Result store│\n"
        "                                                            │  (SQLite)   │\n"
        "                                                            └─────────────┘\n"
        "                                                                 ▲\n"
        "                                  progress.emit()   ┌─────────────┴───────────────┐\n"
        "                                                    │ Redis Pub/Sub               │\n"
        "                                                    │ `agent:progress:{task_id}`  │\n"
        "                                                    └─────────────────────────────┘\n"
        "                                                                 │\n"
        "                                                          SSE GET /runs/{id}/stream\n"
        "```\n"
        "\n"
        "| File | What it does | Maps to |\n"
        "|---|---|---|\n"
        "| `streams.py` | `enqueue` + `consume_loop` over Redis Streams | §5.1 |\n"
        "| `locks.py` | SETNX idempotency lock + Lua release | §5.2 |\n"
        "| `progress.py` | Pub/Sub `ProgressEmitter` + `subscribe()` SSE source | §5.3 |\n"
        "| `store.py` | SQLite result store (drop-in for Mongo) | §5.4 step 5 |\n"
        "| `worker.py` | The six-step `make_handler` wiring all of the above | §5.4 |\n"
        "| `api.py` | FastAPI app — POST /runs, GET /runs/{id}/stream | §5.1 producer surface |\n"
    ),
    md(
        "## 3. Read the lock — the canonical Redis pattern\n"
        "\n"
        "The lock is the **most important** piece. Get this wrong and you get either silent data loss "
        "or double-billing. The lecture spends a whole section (§5.2) on why the release uses a Lua "
        "script."
    ),
    code(
        "import inspect\n"
        "from deepbrief.pipeline.locks import IdempotencyLock, _RELEASE_SCRIPT\n"
        "print(inspect.getsource(IdempotencyLock))\n"
        "print()\n"
        "print(\"_RELEASE_SCRIPT (Lua, runs atomically in Redis):\")\n"
        "print(_RELEASE_SCRIPT)"
    ),
    md(
        "**Why is the release a Lua script?** Three steps in plain Python:\n"
        "\n"
        "```python\n"
        "# WRONG — race condition window between GET and DEL\n"
        "current = await redis.get(lock_key)\n"
        "if current == worker_id:\n"
        "    await redis.delete(lock_key)\n"
        "```\n"
        "\n"
        "Between the `GET` and the `DEL`, the lock can expire and a different worker can claim it. "
        "Your `DEL` then deletes *their* lock. The Lua script bundles GET+DEL into one atomic operation "
        "Redis executes without interruption.\n"
        "\n"
        "**Senior interview tip:** when asked about distributed locks, *mention the Lua script*. It's "
        "the single piece of evidence that you've shipped this pattern instead of read about it."
    ),
    md(
        "## 4. Test the lock in isolation\n"
        "\n"
        "Two workers race for the same task. One wins, one loses. Each releases only its own lock."
    ),
    code(
        "lock = IdempotencyLock(redis, ttl_seconds=10)\n"
        "\n"
        "won_a = await lock.acquire(\"task-001\", worker_id=\"worker-A\")\n"
        "won_b = await lock.acquire(\"task-001\", worker_id=\"worker-B\")\n"
        "print(f\"worker-A acquire: {won_a}\")\n"
        "print(f\"worker-B acquire: {won_b}\")\n"
        "assert won_a and not won_b\n"
        "\n"
        "# worker-B tries to release a lock it doesn't own — Lua script blocks this\n"
        "released_b = await lock.release(\"task-001\", worker_id=\"worker-B\")\n"
        "print(f\"worker-B release (NOT owner): {released_b}\")\n"
        "\n"
        "released_a = await lock.release(\"task-001\", worker_id=\"worker-A\")\n"
        "print(f\"worker-A release (owner):     {released_a}\")\n"
        "assert not released_b and released_a"
    ),
    md(
        "**This is exactly the ToolFlood / runaway-worker defense.** If `worker-A` crashes and its TTL "
        "expires, `worker-B` can acquire — but `worker-A` coming back from a long GC pause **cannot** "
        "delete `worker-B`'s lock. Each worker only owns its own lock.\n"
    ),
    md(
        "## 5. The mock agent handler\n"
        "\n"
        "Before wiring the real LangGraph app, we'll use a **mock agent** for the queue/lock/store demo. "
        "Mock takes 1 second and emits 3 progress events, deterministic — so the pipeline mechanics are "
        "visible without 60s of LLM calls."
    ),
    code(
        "import asyncio\n"
        "\n"
        "from deepbrief.pipeline.progress import ProgressEmitter\n"
        "\n"
        "\n"
        "async def mock_agent(task: dict, emitter: ProgressEmitter) -> dict:\n"
        "    \"\"\"Fake research run — emits 3 progress events, returns a stub draft.\"\"\"\n"
        "    topic = task[\"topic\"]\n"
        "\n"
        "    await emitter.emit(step=1, kind=\"thought\", text=f\"decomposing: {topic}\")\n"
        "    await asyncio.sleep(0.3)\n"
        "\n"
        "    await emitter.emit(step=2, kind=\"tool_call\", tool=\"web_search\", query=topic)\n"
        "    await asyncio.sleep(0.3)\n"
        "\n"
        "    await emitter.emit(step=3, kind=\"thought\", text=\"synthesizing draft\")\n"
        "    await asyncio.sleep(0.3)\n"
        "\n"
        "    return {\n"
        "        \"answer\": f\"# Brief: {topic}\\n\\nMock draft for the pipeline demo.\",\n"
        "        \"draft\": f\"# Brief: {topic}\\n\\nMock draft for the pipeline demo.\",\n"
        "    }\n"
        "\n"
        "print(\"mock_agent defined — emits 3 events, returns in ~1s\")"
    ),
    md(
        "## 6. The six-step worker loop\n"
        "\n"
        "Now the heart of S9 §5.4. Read the source. **The order of these steps is the interview answer.**"
    ),
    code(
        "from deepbrief.pipeline.worker import make_handler\n"
        "from deepbrief.pipeline.store import ResultStore\n"
        "from deepbrief.pipeline.streams import enqueue, consume_loop\n"
        "\n"
        "# Pull out just the handler body — read it carefully\n"
        "src = inspect.getsource(make_handler)\n"
        "print(src)"
    ),
    md(
        "**The order that matters** (S9 §5.5):\n"
        "\n"
        "| Step | Why this order |\n"
        "|---|---|\n"
        "| 1. consume | obvious — can't act without a message |\n"
        "| 2. existing-result check | short-circuits replays of completed work without re-running |\n"
        "| 3. acquire lock | prevents two live workers running the same task |\n"
        "| 4. run agent | the expensive part — protected by lock + completion check |\n"
        "| 5. **persist** | **before ack** — if we ack first then crash before storing, the message is gone but no result exists. Silent data loss. |\n"
        "| 6. **ack** | only after successful persist — if we crash here, the message redelivers and step 2 catches it |\n"
        "| 7. release lock (finally) | **after ack** — if we release first and crash before ack, redelivery goes to a fresh lock and we re-run. By releasing last the new worker either finds the existing result or waits for TTL |\n"
    ),
    md(
        "## 7. Run a worker, enqueue some tasks\n"
        "\n"
        "Start the worker as an asyncio task. Enqueue three tasks. Watch them flow through."
    ),
    code(
        "from deepbrief.pipeline.worker import run_worker\n"
        "\n"
        "store = ResultStore(\"./data/runs.db\")\n"
        "\n"
        "# Kick off the worker — it'll process up to 3 messages then return\n"
        "worker_task = asyncio.create_task(\n"
        "    run_worker(\n"
        "        redis=redis, store=store,\n"
        "        agent_handler=mock_agent,\n"
        "        group=\"deepbrief-nb09\",\n"
        "        stop_after=3,\n"
        "    )\n"
        ")\n"
        "\n"
        "# Enqueue 3 tasks\n"
        "for topic in [\"MCP in 2026\", \"A2A vs MCP\", \"Tool-RAG patterns\"]:\n"
        "    msg_id = await enqueue(redis, {\"topic\": topic, \"query\": topic})\n"
        "    print(f\"enqueued: {topic} → msg={msg_id}\")\n"
        "\n"
        "# Wait for the worker to drain\n"
        "n_processed = await worker_task\n"
        "print(f\"\\nworker processed {n_processed} tasks\")"
    ),
    md(
        "## 8. Verify the SQLite result store"
    ),
    code(
        "# Query all stored runs\n"
        "import sqlite3\n"
        "rows = sqlite3.connect(\"./data/runs.db\").execute(\n"
        "    \"SELECT task_id, query, substr(answer, 1, 60) AS preview FROM runs\"\n"
        ").fetchall()\n"
        "for r in rows:\n"
        "    print(r)"
    ),
    md(
        "## 9. Idempotency demo — enqueue the same task_id twice\n"
        "\n"
        "Real queues at-least-once-deliver. We simulate a redelivery: enqueue the **same** `task_id` "
        "twice, watch the worker do the work once and short-circuit the second time at step 2 "
        "(existing-result check)."
    ),
    code(
        "# Fresh worker for this demo, processes up to 2 messages\n"
        "worker_task = asyncio.create_task(\n"
        "    run_worker(\n"
        "        redis=redis, store=store, agent_handler=mock_agent,\n"
        "        group=\"deepbrief-nb09\", stop_after=2,\n"
        "    )\n"
        ")\n"
        "\n"
        "# Same task_id twice — second is the simulated redelivery\n"
        "SHARED_ID = \"dedupe-demo-001\"\n"
        "await enqueue(redis, {\"topic\": \"WebGPU adoption\", \"task_id\": SHARED_ID})\n"
        "await enqueue(redis, {\"topic\": \"WebGPU adoption\", \"task_id\": SHARED_ID})\n"
        "\n"
        "await worker_task\n"
        "\n"
        "# How many DB rows? Should be exactly 1.\n"
        "count = sqlite3.connect(\"./data/runs.db\").execute(\n"
        "    \"SELECT COUNT(*) FROM runs WHERE task_id = ?\", (SHARED_ID,)\n"
        ").fetchone()[0]\n"
        "print(f\"rows with task_id={SHARED_ID}: {count}\")\n"
        "assert count == 1, \"dedupe failed — should have exactly one row\"\n"
        "print(\"✅ dedupe worked: second delivery short-circuited at the existing-result check\")"
    ),
    md(
        "**Two layers of idempotency, both needed:**\n"
        "\n"
        "- **In-flight protection** — SETNX lock prevents two workers running concurrently\n"
        "- **Completed-task protection** — the existing-result check catches replays of finished work\n"
        "\n"
        "Drop either and you get either double-execution (no lock) or wasted retries that "
        "re-run completed work (no completion check).\n"
    ),
    md(
        "## 10. Progress streaming — what the SSE endpoint would see\n"
        "\n"
        "The FastAPI SSE endpoint (`src/deepbrief/pipeline/api.py::stream_progress`) just subscribes to "
        "the same Pub/Sub channel. We can do the same from the notebook — start a subscriber, kick off "
        "a task, watch the events arrive in real time."
    ),
    code(
        "from deepbrief.pipeline.progress import subscribe\n"
        "\n"
        "PROGRESS_TASK_ID = \"progress-demo-001\"\n"
        "\n"
        "async def collect_progress(task_id, timeout=10):\n"
        "    \"\"\"Subscribe to progress events for task_id, stop on `final` or timeout.\"\"\"\n"
        "    events = []\n"
        "    try:\n"
        "        async with asyncio.timeout(timeout):\n"
        "            async for ev in subscribe(redis, task_id):\n"
        "                events.append(ev)\n"
        "                if ev.get(\"kind\") == \"final\":\n"
        "                    break\n"
        "    except asyncio.TimeoutError:\n"
        "        pass\n"
        "    return events\n"
        "\n"
        "# Start the worker, subscriber, and producer concurrently\n"
        "worker = asyncio.create_task(\n"
        "    run_worker(redis=redis, store=store, agent_handler=mock_agent,\n"
        "               group=\"deepbrief-nb09\", stop_after=1)\n"
        ")\n"
        "subscriber = asyncio.create_task(collect_progress(PROGRESS_TASK_ID))\n"
        "await asyncio.sleep(0.2)   # give the subscriber a moment to attach\n"
        "\n"
        "await enqueue(redis, {\"topic\": \"streaming demo\", \"task_id\": PROGRESS_TASK_ID})\n"
        "\n"
        "events = await subscriber\n"
        "await worker\n"
        "\n"
        "print(f\"received {len(events)} progress events:\")\n"
        "for ev in events:\n"
        "    print(f\"  step={ev.get('step'):>3}  kind={ev.get('kind'):12s}  ts={ev.get('ts'):.2f}\")"
    ),
    md(
        "**This is exactly what an SSE-subscribing browser would see.** The FastAPI endpoint in "
        "`api.py::stream_progress` wraps `subscribe()` in `EventSourceResponse` so the browser receives "
        "a continuous stream. Disconnect handling is automatic — the subscriber's `finally` block "
        "cleans up when the async generator is garbage-collected.\n"
    ),
    md(
        "## 11. (Optional) Wire in the real LangGraph brief\n"
        "\n"
        "Everything we've shown works with any async agent handler. The real version: plug in the "
        "LangGraph app from notebook 07b and run a real research task end-to-end.\n"
        "\n"
        "This takes 30-60 seconds (real LLM + web search). Skip if you don't have a Tavily key.\n"
    ),
    code(
        "from deepbrief.agents.langgraph_brief import build_brief_app, ResearchState\n"
        "\n"
        "brief_app = build_brief_app()\n"
        "\n"
        "async def langgraph_agent(task: dict, emitter: ProgressEmitter) -> dict:\n"
        "    \"\"\"Real agent handler — runs the LangGraph brief and streams events from astream_events.\"\"\"\n"
        "    step = 0\n"
        "    initial: ResearchState = {\n"
        "        \"topic\": task[\"topic\"], \"sub_questions\": [], \"findings\": [], \"draft\": None,\n"
        "    }\n"
        "    final_state = None\n"
        "    async for ev in brief_app.astream_events(initial, version=\"v2\"):\n"
        "        kind = ev[\"event\"]\n"
        "        if kind == \"on_chain_start\" and ev.get(\"name\") in {\"decompose\", \"research\", \"synthesize\"}:\n"
        "            step += 1\n"
        "            await emitter.emit(step=step, kind=\"node_start\", node=ev[\"name\"])\n"
        "        if kind == \"on_chain_end\" and ev.get(\"name\") == \"synthesize\":\n"
        "            final_state = ev[\"data\"][\"output\"]\n"
        "\n"
        "    return {\n"
        "        \"answer\": final_state.get(\"draft\") if final_state else None,\n"
        "        \"draft\": final_state.get(\"draft\") if final_state else None,\n"
        "    }\n"
        "\n"
        "if os.getenv(\"TAVILY_API_KEY\") or os.getenv(\"FORCE_REAL_AGENT\"):\n"
        "    worker = asyncio.create_task(\n"
        "        run_worker(redis=redis, store=store, agent_handler=langgraph_agent,\n"
        "                   group=\"deepbrief-nb09\", stop_after=1)\n"
        "    )\n"
        "    await enqueue(redis, {\"topic\": \"What is MCP?\", \"task_id\": \"real-1\"})\n"
        "    await worker\n"
        "    rec = await store.find_one(\"real-1\")\n"
        "    print(\"=== real LangGraph run via pipeline ===\")\n"
        "    print(rec[\"answer\"][:500] if rec else \"<not stored>\")\n"
        "else:\n"
        "    print(\"skipping real run — set TAVILY_API_KEY to enable\")"
    ),
    md(
        "## 12. What you've built\n"
        "\n"
        "Look back at the lecture S9 §5.1 diagram. You now have **every box**:\n"
        "\n"
        "- ✅ Producer → enqueue + a FastAPI app at `api.py`\n"
        "- ✅ Queue → Redis Stream `agent:runs`, durable + consumer-group aware\n"
        "- ✅ Worker — six-step loop with correct ordering\n"
        "- ✅ Idempotency lock — SETNX claim + Lua release\n"
        "- ✅ Progress emission — Pub/Sub channel per task\n"
        "- ✅ Result store — SQLite (one class swap for MongoDB / Postgres)\n"
        "- ✅ SSE endpoint — `api.py::stream_progress`\n"
        "\n"
        "**This is ~250 lines of Python.** A production team would add: backoff on transient errors, "
        "dead-letter queue for permanent failures (XPENDING + XCLAIM), Prometheus metrics, distributed "
        "tracing via OpenTelemetry GenAI conventions. Each is a known add-on — none change the shape "
        "of what you just built.\n"
    ),
    md(
        "## 13. Cleanup"
    ),
    code(
        "await redis.delete(STREAM)\n"
        "for key in await redis.keys(\"agent:lock:*\"):\n"
        "    await redis.delete(key)\n"
        "# Use aclose() — close() is deprecated in redis-py 5.0.1+\n"
        "await redis.aclose()\n"
        "store.close()\n"
        "print(\"closed Redis + sqlite\")"
    ),
    md(
        "## 14. Self-check (senior-grade)\n"
        "\n"
        "1. Why does step 5 (persist) come before step 6 (ack), not after? Walk through the silent-data-loss scenario if you flip them.\n"
        "2. Why does the lock release happen in `finally` (after ack), and not before ack? Walk through the redelivery scenario if you flip them.\n"
        "3. What end-to-end guarantees give you idempotency? **Two** layers — name both.\n"
        "4. What does the Lua release script do that a plain `GET` + `if owner == me: DEL` doesn't?\n"
        "5. The handler returns `False` on exception (no ack). What kicks in to prevent the next delivery from re-running the same task immediately?\n"
        "6. Which of these would you keep if you migrated from Redis Streams to Kafka? Which would you change?\n"
        "\n"
        "## What's next\n"
        "\n"
        "You've finished the S9 hands-on track. Three places this goes next as portfolio work:\n"
        "\n"
        "- **Dead-letter queue** — when a task fails 3 times, XCLAIM it to a `dead_letter` group; surface to ops.\n"
        "- **Backpressure** — track stream length; refuse new enqueues above a threshold.\n"
        "- **Trace integration** — emit OpenTelemetry GenAI spans (S8 §7.2) so the full request-trace shows worker latency, LLM latency, tool latency.\n"
        "\n"
        "Each is ~half a day of work on top of what you have.\n"
    ),
]

write("notebooks/09_production_pipeline.ipynb", cells)
print("wrote notebooks/09_production_pipeline.ipynb")
